### ISSUE TITLE
With JSXC Owncloud Internal XMPP Server, All Users are Visible to All other Users By Default

### ISSUE THREAD

**Issue by alraban** [jsxc/jsxc#306] opened 2016-03-25 12:56 UTC
I'm using the experimental internal XMPP server with my Owncloud 9.0 deployment.  It appears that all of my users can, by default, see all other users of my owncloud in their roster which is not desirable behavior with large user bases.  

I see that roster groups are not currently supported, but is there any way to change the default so that only contacts or manually added "buddies" will show up in a user's roster? 
##

**Comment by LEDfan** [comment] 2016-03-30 18:39
Hi, thanks for checking out the internal XMPP backend, I hope you like it :smiley:.

@fossxplorer has the same issue, we should definitely find a way to fix this. 
In the future we could provide a setting to no show all users by default. Then you would be able to manually add a user as buddy in the roster.

**Comment by alraban** [comment] 2016-03-31 01:18
It' works great, I've been using it daily (and so have my users) since release a few weeks ago.  It does what I need, so I'd like to use it rather than a separate XMPP server, but I'll need to have a way to separate users.

I'd be fine with a "show no one by default" setting, but best of all woul dbe a way to control who people can see through owncloud groups.  Thanks for looking into it.

**Comment by kas70** [comment] 2016-09-01 07:47
Hey there, thanks for developing the internal backend!
Are there any recent news?

**Comment by MarcelWaldvogel** [comment] 2016-09-01 08:19
With large user bases, we recommend using an external, full-fledged XMPP server. This also gives you the IMHO main advantage of connection to the other XMPP servers in the global federation.

**Comment by wargreen** [comment] 2017-02-28 16:40
With many groups, and +- 100 users, it was best if we can configure jsxc for show only the people of the same groups, without need of add each persons
Is it possible with an external xmpp server?
Thanks !

**Comment by MarcelWaldvogel** [comment] 2017-02-28 17:19
The built-in XMPP server is meant for a few handful of users.
An external XMPP server will show only the users you have invited.
However, the server administrator may define some groups (most XMPP
servers have the possibility).
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/jsxc/jsxc
> ","title":"jsxc/jsxc","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/ass
> ets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in
> GitHub","url":"https://github.com/jsxc/jsxc"}},"updates":{"snippets":
> [{"icon":"PERSON","message":"@wargreen in #306: With many groups, and
> +- 100 users, it was best if we can configure jsxc for show only the
> people of the same groups, without need of add each persons\r\nIs it
> possible with an external xmpp server?\r\nThanks
> !"}],"action":{"name":"View
> Issue","url":"https://github.com/jsxc/jsxc/issues/306#issuecomment-
> 283093171"}}}

**Comment by putt1ck** [comment] 2017-03-13 08:58
Control of who can get access to chat (client) could be group-based with built-in or external server. External server could limit access to use by shared authentication with NextCloud/OwnCloud server(s), and in some scenarios by not being available to the Internet. 

Our particular interest is for use within schools, to enable chat without enabling "chat with anybody"), and in that situation (and if built-inl XMPP server can't scale) would use external server with no (or strictly controlled, for chat with other schools) Internet access.

**Comment by sualko** [comment] 2017-03-14 09:52
Currently this is out of scope for us, but pull requests are always welcome.

**Closed** 2018-02-10 10:27 UTC
Labels: enhancement, internal-backend, nextcloud

**Comment by LEDfan** [comment] 2018-02-10 10:29
@alraban @putt1ck @kas70 @Schmuuu This is now implemented and can be tested!

Please test the attached archive and give some feedback, thanks.
[ojsxc-3.3.2.tar.gz](https://github.com/jsxc/jsxc/files/1713265/ojsxc-3.3.2.tar.gz)

**Comment by putt1ck** [comment] 2018-02-10 11:17
Great job. Thanks. Will try and test once we've got our NC13 upgrades all done.

**Comment by Schmuuu** [comment] 2018-02-10 12:11
Hi @LEDfan 
Thanks a lot! I've been really waiting for this feature!
I just tested it and I see some issues.

### The Setup
#### Group "Notification":
+ user1
+ admin

#### Group "family":
+ user1
+ user2

#### Group "user1":
+ user1
+ userX

#### Group "user2":
+ user2
+ userY
-------------------------

### The situation
+ admin doesn't see anybody in the contact list (of the chat)
+ user1 sees admin in his contact list
+ when user1 writes admin a message, the message is not received by admin
+ when user1 writes user2 a message, the message is not received by user2
+ for all the cases where the message is not delivered, there is a log entry: 
     - "User user1 is trying to send a message to user2 but this isn't allowed"
     - "User user1 is trying to send a message to admin but this isn't allowed"

**Comment by Schmuuu** [comment] 2018-02-11 12:57
Hi @LEDfan 
Thank you very much for providing the next version so quickly. I tested it a while now.

First of all: chatting with contacts works again! 👍 
Second: not all contacts are shown to the users 👍 

However, the users that show up in the contact list is not complete and I struggle to find a pattern here.

ncadmin member of group:
+ admin
+ Notification

User1 member of group:
+ Notification
+ demo
+ family
+ Friends-group

User2 member of group:
+ family
+ Friends-group (group admin)

User3 member of group:
+ family
+ Group-User3 (group admin)

User ncadmin sees nobody, his contact list is empty. While most of the users shouldn't see ncadmin in their contact list, User1 actually should and that is not the case.

User3 is not seen by anybody (neither User1 nor User2), although being in the family group (where nearly every user belongs to, except admin and demo users).

For User1 and User2 there were some more inconsistencies as well, but after running
occ ojsxc:refresh-roster
it looked fine (except the problem with User3).


Is it possible that groups are picked randomly? Meaning that if a user is member of many groups, the app picks the first/ last group in the list and builds up the contact list depending on that first/ last group and every other group membership is ignored? That's the only reason I can think of right now, that might explain why it works for the most part and only some users are left behind.

Thank you so much for taking care of this issue. I love to see how the chat app improves further and further 👍

**Comment by LEDfan** [comment] 2018-02-11 16:14
@Schmuuu although your detailed report I can't reproduce the issue. 
When you login as `ncadmin` can you click on the ContactsMenu icon and see all other users there? 
![selectie_847](https://user-images.githubusercontent.com/2996275/36075387-91224a06-0f4e-11e8-8cb5-871037f7c531.png)

The app is using the same API for retrieving the users in theory if they show up there they should be found by the app.

Also are you using this server option for some groups:
https://cloud.githubusercontent.com/assets/19711361/25737875/5b36b358-317a-11e7-8331-d10380e6e27d.png ? This also affects the ContactsMenu and thus this app.

**Comment by Schmuuu** [comment] 2018-02-11 16:34
@LEDfan 
No, I'm not using that option:
![grafik](https://user-images.githubusercontent.com/26191454/36075569-199c6a7c-0f51-11e8-8cf5-8269b26cfdbf.png)

Indeed, when I look at the contacts of ncadmin, this list is empty as well.
![grafik](https://user-images.githubusercontent.com/26191454/36075581-4e1e5b98-0f51-11e8-8b76-a5627196a8da.png)

![grafik](https://user-images.githubusercontent.com/26191454/36075590-5d0eae1e-0f51-11e8-8454-3154fca034d0.png)


The really strange thing here is:
user "demo1" sees all three members of group "demo" in the contact list of the chat app (demo-admin, demo2, User1), but in the contacts menu however he can only see the users demo2 and demo-admin. User1 is missing there.

**Comment by Schmuuu** [comment] 2018-02-13 23:13
Hi @LEDfan 

I noticed another strange thing: different devices, different browsers, but the same user and I also see different contacts in my list.

First, the normal user User1 (same User1 as in the examples above):
![ojsxc_1](https://user-images.githubusercontent.com/26191454/36178920-c453d700-111a-11e8-898f-6397dd758766.jpg)

Please notice that on the left side, User1 can see Demo-Admin and Demo-User, but no Admin and "J" like on the right side. User1 should actually see **all** these users.

Second, the admin user:
![ojsxc_2](https://user-images.githubusercontent.com/26191454/36178937-d3c85206-111a-11e8-9983-a99ce6037020.jpg)

In this screenshot there is pretty much everything wrong :D 
User Admin should actually see only one of the users with "K".

With the both users still logged in on different devices and different browser (Firefox and Edge) I ran
occ ojsxc:refresh-roster 
again, cleared the browser cash and did a full reload of the web pages. It didn't have any effects on the contact lists.

I try to collect some more debug information tomorrow, but hopefully this is already helping.

**Comment by Schmuuu** [comment] 2018-02-14 08:33
Hi @LEDfan 

I just checked the browser debug console and get the following content when I'm logged in as admin who sees **no contacts** at all:

```
State changed to INITIATING
jsxc.min.js:13:1885
State changed to PREVCONFOUND
jsxc.min.js:13:1885
check master
jsxc.min.js:13:1885
Source-Map-Error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Address: https://sub.domain.tld/core/vendor/core.js?v=3b886e95-21
Source-Map-Address: purify.min.js.map
[Learn More]
Source-Map-Error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Address: https://sub.domain.tld/apps/ojsxc/js/jsxc/jsxc.min.js?v=3b886e95-21
Source-Map-Address: jsxc.min.js.map
[Learn More]
I am master.
jsxc.min.js:13:1885
State changed to ESTABLISHING
jsxc.min.js:13:1885
Try to attach
jsxc.min.js:13:1885
SID: internal
jsxc.min.js:13:1885
ATTACHED: null
jsxc.min.js:13:1885
Discover muc service
jsxc.min.js:13:1885
UI State changed to INITIATING
jsxc.min.js:13:1885
Waiting for server capabilities
jsxc.min.js:13:1885
Request server capabilities
jsxc.min.js:13:1885
No saved buddylist.
jsxc.min.js:13:1885
UI State changed to READY
jsxc.min.js:13:1885
DSA key loaded
jsxc.min.js:13:1885
State changed to READY
jsxc.min.js:13:1885
Presence (User1@sub.domain.tld/internal): online
jsxc.min.js:13:1885
Presence (User2@sub.domain.tld/internal): offline
jsxc.min.js:13:1885
Presence (User3@sub.domain.tld/internal): offline
jsxc.min.js:13:1885
Presence (User4@sub.domain.tld/internal): offline
jsxc.min.js:13:1885
Presence (User5@sub.domain.tld/internal): offline
jsxc.min.js:13:1885
Presence (User6@sub.domain.tld/internal): offline
jsxc.min.js:13:1885
Presence (demo@sub.domain.tld/internal): offline
jsxc.min.js:13:1885
Presence (User1@sub.domain.tld/internal): offline
jsxc.min.js:13:1885
Presence (User3@sub.domain.tld/internal): offline
jsxc.min.js:13:1885
Presence (User8@sub.domain.tld/internal): offline
jsxc.min.js:13:1885
Presence (User4@sub.domain.tld/internal): offline
jsxc.min.js:13:1885
Presence (User2@sub.domain.tld/internal): offline
jsxc.min.js:13:1885
Presence (User5@sub.domain.tld/internal): offline
jsxc.min.js:13:1885
Presence (User6@sub.domain.tld/internal): offline
jsxc.min.js:13:1885
Presence (User7@sub.domain.tld/internal): offline
jsxc.min.js:13:1885
Presence (User9@sub.domain.tld/internal): offline
jsxc.min.js:13:1885
Presence (User10@sub.domain.tld/internal): offline
jsxc.min.js:13:1885
Presence (User11@sub.domain.tld/internal): offline
jsxc.min.js:13:1885
Presence (User12@sub.domain.tld/internal): offline
jsxc.min.js:13:1885
Presence (Demo-Admin@sub.domain.tld/internal): offline
jsxc.min.js:13:1885
Presence (Demo-Nutzer1@sub.domain.tld/internal): offline
jsxc.min.js:13:1885
Presence (User10@sub.domain.tld/internal): offline
jsxc.min.js:13:1885
Presence (User9@sub.domain.tld/internal): offline
```
So there is this Source-Map-Error, where I'm not sure if this is related.

And then for **every** user on the server I receive the presence. Strange though: I receive the presence of user "demo" who doesn't exist on the server (not to confuse with the users "Demo-Nutzer" and "Demo-Admin"). The user demo existed in the past, but was already deleted - and doesn't exist in the DB table oc_users.

What I just noticed as well:
The DB table oc_ojsxc_stanzas contains a lot entries. While I don't know what this table is used for, it seems strange that the column "from" is usually empty. Only two of these 619 entries have a value in column "from" and this is one time "Admin" and one time "User1".

With the other entries like
`    ID | _BLANK_ | USERX | STANZA`
the stanza varies between 
`    .*subscription="both".* `
and 
`    .*subscription="remove".*`

In the table oc_ojsxc_presence I see every user of the server (plus the no longer existing user "demo"). 
Most users exist twice as:
user
User

Some users however only exist in this table written in small letters. So for 15 users, there are 24 entries in this table.

I hope this will help you help me :D 

Thanks a lot again for your investigation and for creating this awesome app!

**Comment by Schmuuu** [comment] 2018-02-14 09:28
And maybe the debug output from the log is useful:

```
Debug	ojsxc	Receiving {ncadmin} : <body rid='123467' xmlns='http://jabber.org/protocol/httpbind' sid='internal'><iq from='ncadmin@sub.domain.tld/internal' to='sub.domain.tld' type='get' xmlns='jabber:client' id='3ecf3a2c-0152-4815-8457-d82fe41b7ee1:sendIQ'><query xmlns='http://jabber.org/protocol/disco#items'/></iq></body>	2018-02-14T08:36:49+0100
Debug	ojsxc	Sending {User1} : <presence xmlns="jabber:client" from="ncadmin@sub.domain.tld/internal" to="User1@sub.domain.tld/internal"/>	2018-02-14T08:36:49+0100
Debug	ojsxc	Receiving {ncadmin} : <body rid='123466' xmlns='http://jabber.org/protocol/httpbind' sid='internal'><iq from='ncadmin@sub.domain.tld/internal' to='ncadmin@sub.domain.tld' type='get' xmlns='jabber:client' id='1be4c641-382c-422f-9340-2b855b8f2509:sendIQ'><query xmlns='http://jabber.org/protocol/disco#info'/></iq><iq type='get' xmlns='jabber:client' id='cc590f96-6c43-492d-a2d9-2ab4a8fadd49:sendIQ'><vCard xmlns='jabber:vcard-temp'/></iq></body>	2018-02-14T08:36:48+0100
Debug	ojsxc	Sending {ncadmin} : <presence type="unavailable" from="User2@sub.domain.tld/internal" to="ncadmin@sub.domain.tld/internal" xmlns="jabber:client"/>	2018-02-14T08:36:48+0100
Debug	ojsxc	Sending {ncadmin} : <presence type="unavailable" from="User3@sub.domain.tld/internal" to="ncadmin@sub.domain.tld/internal" xmlns="jabber:client"/>	2018-02-14T08:36:48+0100
Debug	ojsxc	Sending {ncadmin} : <presence type="unavailable" from="Demo-Nutzer1@sub.domain.tld/internal" to="ncadmin@sub.domain.tld/internal" xmlns="jabber:client"/>	2018-02-14T08:36:48+0100
Debug	ojsxc	Sending {ncadmin} : <presence type="unavailable" from="Demo-Admin@sub.domain.tld/internal" to="ncadmin@sub.domain.tld/internal" xmlns="jabber:client"/>	2018-02-14T08:36:48+0100
...
Debug	ojsxc	Sending {ncadmin} : <presence xmlns="jabber:client" from="User1@sub.domain.tld/internal" to="ncadmin@sub.domain.tld/internal"/>	2018-02-14T08:36:48+0100
Debug	ojsxc	Storing {ncadmin} : <presence xmlns="jabber:client" from="ncadmin" to="User1"/>	2018-02-14T08:36:48+0100
Debug	ojsxc	Receiving {ncadmin} : <body rid='123465' xmlns='http://jabber.org/protocol/httpbind' sid='internal'><iq from='ncadmin@sub.domain.tld/internal' to='sub.domain.tld' type='get' xmlns='jabber:client' id='8d28d9c1-dc0a-4122-ba37-8fdb9e090d42:sendIQ'><query xmlns='http://jabber.org/protocol/disco#info' node='undefined#undefined'/></iq><presence xmlns='jabber:client'><c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='http://jsxc.org/' ver='UEMHBlT9XVU7FUwfm/6rl815MUE='/></presence></body>
```

I didn't change any IDs or numbers in this output. The output "body rid='123467'" is really written that way in the log.

**Comment by LEDfan** [comment] 2018-02-21 09:52
@Schmuuu thanks for your extensive information!

> Indeed, when I look at the contacts of ncadmin, this list is empty as well.

This may indicate actually that this is a sever bug, since the contacts menu contents is generated in the core of Nextcloud, I'll try to investigate this more.

> I noticed another strange thing: different devices, different browsers, but the same user and I also see different contacts in my list.

When you load Nextcloud and JSXC the "roster" (the user list) is cached in the browser. However with this new version changes are made to the roster and these are pushed to the clients using "roster-push" (automatically generated or using  the occ command). However when the user has multiple connections, the roster push is received by only one client. 
You can clear the cache by logging out from Nextcloud, opening the browser console and run `localStorage.clear` and login again.
