### ISSUE TITLE
How to do audio/video call with conversations android app?

### ISSUE THREAD

**Issue by joe-average-user** [jsxc/jsxc#914] opened 2020-06-16 14:32 UTC
**Is your feature request related to a problem? Please describe.**

We did not manage to do calls to an xmpp conversations party. Calls to/from jsxc are working, calls conversations/conversations are working as well.

**Is your feature request related to a specific XEP?**

No idea, the call signaling works, the app (conversations) shows the incoming call. If you try to enter it though it breaks and jsxc shows some error. Simple to test.

**Describe the solution you'd like**

**Additional context**

**Comment by DanScharon** [comment] 2020-06-16 16:44
duplicate of #890

**Comment by ostasevych** [comment] 2020-06-20 09:43
I suggest to close this issue, as with version 4.1.0 the calls from Conversations/Pix-Art are received in JSXC and vice versa.

**Comment by joe-average-user** [comment] 2020-06-20 09:49
You should elaborate this, because in my setup this does not work. And the problem is really not that the calls are not _received_. They are, but you cannot pick up such a call at our setup. Both ways initiated this does not work. Please explain the basics of a setup where this does work.

**Comment by joe-average-user** [comment] 2020-06-20 09:53
Our setup consists of an ejabberd 20.04 xmpp server, with separate turn/stun server. All calls from/to conversations app work. All calls from/to jsxc work. No call from conversations to jsxc works, and not from jsxc to conversations.

**Comment by ostasevych** [comment] 2020-06-20 11:17
What I see in Nextcloud:

inbound video call
![image](https://user-images.githubusercontent.com/5199030/85200491-89b60200-b300-11ea-8589-c272844f7fd8.png)

inbound audio call
![image](https://user-images.githubusercontent.com/5199030/85200514-ba963700-b300-11ea-8533-3bea2062195c.png)

Perhaps you have to allow pop-up windows?...

**Comment by joe-average-user** [comment] 2020-06-20 15:34
Hello, thanks for the comment. I checked the popup setup and they are allowed, but don't show up.What nextcloud version are you using?

**Comment by ostasevych** [comment] 2020-06-20 16:45
> Hello, thanks for the comment. I checked the popup setup and they are allowed, but don't show up.What nextcloud version are you using?

19.0.0.12 with prosody.

**Comment by joe-average-user** [comment] 2020-06-21 07:18
I checked that, we are too on 19.0.0.12.
Are there any special things to configure in your prosody server? Anything related to jingle?

**Comment by joe-average-user** [comment] 2020-06-21 07:56
Are we sure that jsxc supports an external stun(s)/turn(s) server? Or does it imply that the xmpp server (address) is a stun/turn server as well? We are using a turn server with another IP address ...
Our ejabberd is not working as turn.

**Comment by sualko** [comment] 2020-06-21 10:12
JSXC is using stun/turn, but as the developer from Conversations pointed out, see #915, the our Jingle implementation is generating invalid jingle stanzas in Firefox. If you have issues in Chrome as well, please post your setup including browser version to #890, because I will close this as a duplicate.

**Closed by sualko** 2020-06-21 10:12 UTC
Labels: enhancement
