### ISSUE TITLE
User connects, but presence cannot be set

### ISSUE THREAD

**Issue by jpehman** [jsxc/jsxc#884] opened 2020-04-27 16:26 UTC
### Expected behavior
User is connected and online.

### Actual behavior
User is connected, but cannot go online.

### Steps to reproduce the behavior
1. Call start with appropriate bosh, user/resource, and password. (no user form)
2. connectionCallback returns the username
3. The "waiting" icon appears next to the presence status (which says Online)
4. "You are currently offline" is displayed beneath the roster.
5. Open the presence menu.
6. Click "Online".
7. A login form is presented or if jsxc.options.onUserRequestToGoOnline is defined, the method is called.

### Environment
- **JSXC version: 4.0.0
- **Host system and version: custom integration
- **Browser vendor and version: IE11, Edge, Chrome, Brave, Firefox latest
- **Any browser plugins enabled?** 
- **XMPP server vendor and version: MDaemon v20
- **Is your XMPP server working with other clients as expected? yes, Trillian works

#### JSXC

```[Debug] State changed to ESTABLISHING
 
[Debug] Try to establish a new connection.
 
[Debug] Strophe Connection Status:  CONNECTING
  
[Debug] > <body rid=​"1998305523" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" to=​"jedi.mail" xml:lang=​"en" wait=​"60" hold=​"1" content=​"text/​xml;​ charset=utf-8" ver=​"1.6" xmpp:version=​"1.0" xmlns:xmpp=​"urn:​xmpp:​xbosh">​</body>​
 
[Debug] <  < <body xmlns:stream=​"http:​/​/​etherx.jabber.org/​streams" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" from=​"jedi.mail" hold=​"1" wait=​"60" sid=​"wcses-1527624722566917" ack=​"1998305523">​<stream:features>​<mechanisms xmlns=​"urn:​ietf:​params:​xml:​ns:​xmpp-sasl">​<mechanism>​PLAIN​</mechanism>​</mechanisms>​<auth xmlns=​"http:​/​/​jabber.org/​features/​iq-auth">​</auth>​<bind xmlns=​"urn:​ietf:​params:​xml:​ns:​xmpp-bind">​</bind>​<session xmlns=​"urn:​ietf:​params:​xml:​ns:​xmpp-session">​<optional>​</optional>​</session>​</stream:features>​</body>​

 
[Debug] > <body rid=​"1998305524" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"wcses-1527624722566917">​<auth xmlns=​"urn:​ietf:​params:​xml:​ns:​xmpp-sasl" mechanism=​"PLAIN">​"YW5ha2luLnNreXdhbGtlckBqZWRpLm1haWwAYW5ha2luLnNreXdhbGtlcgA5WUpwV04vdStwNVVjZkxYb0xGZkFUa3BkVXB1Uk83R0dJekcxbmNYbmxaUnY4VEQzZkl5OGZrTFBuTlBWbmcwcTNBeEUydm1vQzExRm1ncGFic1NrejNURk1tdDM3cTJMWUNIRDdnOEdHbTQvK2J3RGZXU1h3PT0="</auth>​</body>​
 
[Debug] < <body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" ack=​"1998305524" sid=​"wcses-1527624722566917">​<success xmlns=​"urn:​ietf:​params:​xml:​ns:​xmpp-sasl">​</success>​</body>​
 
[Debug] > <body rid=​"1998305525" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"wcses-1527624722566917" to=​"jedi.mail" xml:lang=​"en" xmpp:restart=​"true" xmlns:xmpp=​"urn:​xmpp:​xbosh">​</body>​
 
[Debug] < <body xmlns:stream=​"http:​/​/​etherx.jabber.org/​streams" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" from=​"jedi.mail" hold=​"1" wait=​"60" sid=​"wcses-1527624722566917" ack=​"1998305525">​<stream:features>​<mechanisms xmlns=​"urn:​ietf:​params:​xml:​ns:​xmpp-sasl">​<mechanism>​PLAIN​</mechanism>​</mechanisms>​<auth xmlns=​"http:​/​/​jabber.org/​features/​iq-auth">​</auth>​<bind xmlns=​"urn:​ietf:​params:​xml:​ns:​xmpp-bind">​</bind>​<session xmlns=​"urn:​ietf:​params:​xml:​ns:​xmpp-session">​<optional>​</optional>​</session>​</stream:features>​</body>​
 
[Debug] > <body rid=​"1998305526" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"wcses-1527624722566917">​<iq type=​"set" id=​"_bind_auth_2" xmlns=​"jabber:​client">​<bind xmlns=​"urn:​ietf:​params:​xml:​ns:​xmpp-bind">​<resource>​vOuqeQqWc1sRI7LCMWc1​</resource>​</bind>​</iq>​</body>​
 
[Debug] < <body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" ack=​"1998305526" sid=​"wcses-1527624722566917">​<iq type=​"result" id=​"_bind_auth_2" to=​"vOuqeQqWc1sRI7LCMWc1/​wcses-1527624722566917">​<bind xmlns=​"urn:​ietf:​params:​xml:​ns:​xmpp-bind">​<jid>​anakin.skywalker@jedi.mail/vOuqeQqWc1sRI7LCMWc1​</jid>​</bind>​</iq>​</body>​
 [Debug] > <body rid=​"1998305527" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"wcses-1527624722566917">​…​</body>​
 
[Debug] < <body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" ack=​"1998305527" sid=​"wcses-1527624722566917">​<iq type=​"result" id=​"_session_auth_2" to=​"anakin.skywalker@jedi.mail/​vOuqeQqWc1sRI7LCMWc1">​</iq>​</body>​
 
[Debug] XMPP connection ready
[Debug] destroy old account with uid anakin.skywalker@jedi.mail 
 
[Debug] Instanciate otr for account anakin.skywalker@jedi.mail
  
[Debug] Instanciate omemo for account anakin.skywalker@jedi.mail 
 
[Warn] Error: LibSignal is not available 
 
[Debug] Instanciate receipts for account anakin.skywalker@jedi.mail
 
[Debug] Instanciate notification for account anakin.skywalker@jedi.mail
 
[Debug] Instanciate me-command for account anakin.skywalker@jedi.mail
 
[Debug] Instanciate mam for account anakin.skywalker@jedi.mail
 
[Debug] Instanciate chat-state for account anakin.skywalker@jedi.mail
 
[Debug] Instanciate http-upload for account anakin.skywalker@jedi.mail
 
[Debug] Instanciate vcard-avatars for account anakin.skywalker@jedi.mail
 
[Debug] Instanciate bookmarks for account anakin.skywalker@jedi.mail
 
[Debug] query master
 
[Debug] UI State changed to INITIATING
 
[Debug] Claim master
 
[Debug] I am master
 
[Debug] State changed to ESTABLISHING
 
[Debug] Try to attach old connection.
 
[Debug] > <body rid=​"1998305528" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"wcses-1527624722566917">​</body>​
 
[Debug] XMPP connection ready
 
[Debug] > <body rid=​"1998305529" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"wcses-1527624722566917">​<iq type=​"get" xmlns=​"jabber:​client" id=​"51277f72-c128-4418-90ca-f72d68486827:​sendIQ">​<query xmlns=​"jabber:​iq:​roster" ver>​</query>​</iq>​<iq xmlns=​"jabber:​client" type=​"get" id=​"b68300d5-aef4-40c1-91da-ed8b2a2184b8:​sendIQ">​<pubsub xmlns=​"http:​/​/​jabber.org/​protocol/​pubsub">​…​</pubsub>​</iq>​</body>​

[Debug] < <body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" ack=​"1998305529" sid=​"wcses-1527624722566917">​<iq id=​"51277f72-c128-4418-90ca-f72d68486827:​sendIQ" type=​"result">​<query xmlns=​"jabber:​iq:​roster">​<item jid=​"luke.skywalker@jedi.mail" subscription=​"none" ask=​"subscribe" name=​"Luke Skywalker">​</item>​<item jid=​"chewbacca@jedi.mail" subscription=​"none" ask=​"subscribe" name=​"Chewbacca">​</item>​</query>​</iq>​</body>​
 
[Debug] Load roster <iq id=​"51277f72-c128-4418-90ca-f72d68486827:​sendIQ" type=​"result">​…​</iq>​
 
[Debug] < <body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" ack=​"1998305528" sid=​"wcses-1527624722566917">​<iq from type=​"error" to id=​"b68300d5-aef4-40c1-91da-ed8b2a2184b8:​sendIQ">​<pubsub xmlns=​"http:​/​/​jabber.org/​protocol/​pubsub">​</pubsub>​<error type=​"cancel">​<service-unavailable xmlns=​"urn:​ietf:​params:​xml:​ns:​xmpp-stanzas">​</service-unavailable>​</error>​</iq>​</body>​
 
[Info] <iq xmlns="http://jabber.org/protocol/httpbind" from="" type="error" to="" id="b68300d5-aef4-40c1-91da-ed8b2a2184b8:sendIQ">
<pubsub xmlns="http://jabber.org/protocol/pubsub"/>
<error type="cancel">
<service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
</error>
</iq>
 
[Debug] Send presence <presence xmlns="jabber:client"><c hash="sha-1" node="https://jsxc.org" ver="/kiuBaNl4gAxg/MCGqs3pby7Ho4=" xmlns="http://jabber.org/protocol/caps"/></presence>
 
[Debug] > <body rid=​"1998305530" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"wcses-1527624722566917">​<presence xmlns=​"jabber:​client">​<c xmlns=​"http:​/​/​jabber.org/​protocol/​caps" hash=​"sha-1" node=​"https:​/​/​jsxc.org" ver=​"/​kiuBaNl4gAxg/​MCGqs3pby7Ho4=">​</c>​</presence>​</body>​

[Debug] < <body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" ack=​"1998305530" sid=​"wcses-1527624722566917">​</body>​
```

#### XMPP

```
in> <body content="text/xml; charset=utf-8" hold="1" rid="1998305523" to="jedi.mail" ver="1.6" wait="60" xml:lang="en" xmlns="http://jabber.org/protocol/httpbind" xmlns:xmpp="urn:xmpp:xbosh" xmpp:version="1.0"/>

out< <body xmlns:stream="http://etherx.jabber.org/streams" xmlns="http://jabber.org/protocol/httpbind" from="jedi.mail" hold="1" wait="60" sid="wcses-1527624722566917" ack="1998305523"><stream:features><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism></mechanisms><auth xmlns="http://jabber.org/features/iq-auth"/><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/><session xmlns="urn:ietf:params:xml:ns:xmpp-session"><optional/></session></stream:features></body>

in> <body rid="1998305524" sid="wcses-1527624722566917" xmlns="http://jabber.org/protocol/httpbind"><auth mechanism="PLAIN" xmlns="urn:ietf:params:xml:ns:xmpp-sasl">YW5ha2luLnNreXdhbGtlckBqZWRpLm1haWwAYW5ha2luLnNreXdhbGtlcgA5WUpwV04vdStwNVVjZkxYb0xGZkFUa3BkVXB1Uk83R0dJekcxbmNYbmxaUnY4VEQzZkl5OGZrTFBuTlBWbmcwcTNBeEUydm1vQzExRm1ncGFic1NrejNURk1tdDM3cTJMWUNIRDdnOEdHbTQvK2J3RGZXU1h3PT0=</auth></body>

out< <body xmlns="http://jabber.org/protocol/httpbind" ack="1998305524" sid="wcses-1527624722566917"><success xmlns="urn:ietf:params:xml:ns:xmpp-sasl"/></body>

in> <body rid="1998305525" sid="wcses-1527624722566917" to="jedi.mail" xml:lang="en" xmlns="http://jabber.org/protocol/httpbind" xmlns:xmpp="urn:xmpp:xbosh" xmpp:restart="true"/>

out< <body xmlns:stream="http://etherx.jabber.org/streams" xmlns="http://jabber.org/protocol/httpbind" from="jedi.mail" hold="1" wait="60" sid="wcses-1527624722566917" ack="1998305525"><stream:features><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism></mechanisms><auth xmlns="http://jabber.org/features/iq-auth"/><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/><session xmlns="urn:ietf:params:xml:ns:xmpp-session"><optional/></session></stream:features></body>

in> <body rid="1998305526" sid="wcses-1527624722566917" xmlns="http://jabber.org/protocol/httpbind"><iq id="_bind_auth_2" type="set" xmlns="jabber:client"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><resource>vOuqeQqWc1sRI7LCMWc1</resource></bind></iq></body>

out< <body xmlns="http://jabber.org/protocol/httpbind" ack="1998305526" sid="wcses-1527624722566917"><iq type="result" id="_bind_auth_2" to="vOuqeQqWc1sRI7LCMWc1/wcses-1527624722566917"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><jid>anakin.skywalker@jedi.mail/vOuqeQqWc1sRI7LCMWc1</jid></bind></iq></body>

in< <body rid="1998305527" sid="wcses-1527624722566917" xmlns="http://jabber.org/protocol/httpbind"><iq id="_session_auth_2" type="set" xmlns="jabber:client"><session xmlns="urn:ietf:params:xml:ns:xmpp-session"/></iq></body>

out> <body xmlns="http://jabber.org/protocol/httpbind" ack="1998305527" sid="wcses-1527624722566917"><iq type="result" id="_session_auth_2" to="anakin.skywalker@jedi.mail/vOuqeQqWc1sRI7LCMWc1"/></body>

in< <body rid="1998305529" sid="wcses-1527624722566917" xmlns="http://jabber.org/protocol/httpbind"><iq id="51277f72-c128-4418-90ca-f72d68486827:sendIQ" type="get" xmlns="jabber:client"><query ver="" xmlns="jabber:iq:roster"/></iq><iq id="b68300d5-aef4-40c1-91da-ed8b2a2184b8:sendIQ" type="get" xmlns="jabber:client"><pubsub xmlns="http://jabber.org/protocol/pubsub"><items node="storage:bookmarks"/></pubsub></iq></body>

out> <body xmlns="http://jabber.org/protocol/httpbind" ack="1998305529" sid="wcses-1527624722566917"><iq id="51277f72-c128-4418-90ca-f72d68486827:sendIQ" type="result"><query xmlns="jabber:iq:roster"><item jid="luke.skywalker@jedi.mail" subscription="none" ask="subscribe" name="Luke Skywalker"/><item jid="chewbacca@jedi.mail" subscription="none" ask="subscribe" name="Chewbacca"/></query></iq></body>
```

#### Host

no

**Comment by sualko** [comment] 2020-04-30 13:34
I can reproduce this while attaching an existing connection. It will be fixed in the next release. Thanks for reporting.

**Comment by jpehman** [comment] 2020-04-30 19:05
> I can reproduce this while attaching an existing connection. It will be fixed in the next release. Thanks for reporting.

Thank you sualko! :)

**Comment by sualko** [comment] 2020-05-04 13:42
After fixing my attach issue, I saw that your issue appears with jid and password and I can't reproduce this behavior. Did you try it with another xmpp server? Do you have an idea how I could reproduce it?

**Comment by jpehman** [comment] 2020-05-04 15:33
I have not tried it with another XMPP server. I'll try it with OpenFire.

The issue occurs when jsxc start is called without a form being submitted by the user. 

Instead, the user clicks a button which gets a temporary password for the connection. The connection succeeds, but the presence response from the server is not applied by the client, so the client sits in a presence changing/loading state.

It's the same whether it's an existing connection or not. That is, I get the same behavior with either of these:

```
jsxc.start(xmppUrl, `${user}/${self.resourceID}`, userPassword)
```

or

```
let account = lStore.get(`jsxc2:${user}:connection`);
if (account) {
  account = JSON.parse(account);
  if (account.jid) {
    self.jsxc.start(self.xmppUrl, account.jid, account.sid, account.rid);
    return;
  }

```

I thinks this part of the debug log tells the story:

```
[Debug] > 
<body rid=​"1998305530" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"wcses-1527624722566917">​
  <presence xmlns=​"jabber:​client">
    ​<c xmlns=​"http:​/​/​jabber.org/​protocol/​caps" hash=​"sha-1" node=​"https:​/​/​jsxc.org" ver=​"/​kiuBaNl4gAxg/​MCGqs3pby7Ho4=">​</c>​
  </presence>​
</body>​

[Debug] < 
<body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" ack=​"1998305530" sid=​"wcses-1527624722566917">​</body>​
```

Note that the server acknowledges the presence, yet the client does not change the presence state. Is the server's response inadequate?

**Comment by jpehman** [comment] 2020-05-04 16:54
Just tried out OpenFire using the same paradigm. OpenFire responds differently from our BOSH server:

**Comment by sualko** [comment] 2020-05-04 19:36
Looks like your server isn't standard conform, because the presence should be broadcasted to all connected resources:

> The user's server MUST also broadcast initial presence from the
   user's newly available resource to all of the user's available
   resources, including the resource that generated the presence
   notification in the first place (i.e., an entity is implicitly
   subscribed to its own presence).

https://tools.ietf.org/html/rfc6121#section-4.2.2

I think this is nothing we can fix in JSXC, therefore I close this issue. If you need any further assistance, please reply.

**Closed by sualko** 2020-05-04 19:36 UTC
Labels: bug

**Comment by jpehman** [comment] 2020-05-05 14:58
Thanks for looking into this sualko.

**Comment by jpehman** [comment] 2020-05-06 13:55
One last update. 

I just want to confirm that it was indeed the server failing to respond with the initial presence to the resource that generated it.

**Comment by sualko** [comment] 2020-05-06 14:16
> I just want to confirm that it was indeed the server failing to respond with the initial presence to the resource that generated it.

Thanks for the update and I'm glad you found the reason.
