### ISSUE TITLE
No more scrollbars or mousewheel scroll support?

### ISSUE THREAD

**Issue by poVoq** [jsxc/jsxc#918] opened 2020-06-22 18:36 UTC
### Expected behavior
As before, I would like to scroll up in chats or MUCs to see old messages

### Actual behavior
Seems to be impossible in latest version (4.4.1) on Firefox in Nextcloud19.

### Steps to reproduce the behavior
1. Start JSXC in Nextcloud
2. Open a Chat or MUC
3. Try to scroll the messages.

### Environment
- **JSXC version:*4.4.1* 
- **Host system and version:*Nextcloud19* 
- **Browser vendor and version:*Firefox 77.0.1 Linux* 
- **Any browser plugins enabled?*no* 
- **XMPP server vendor and version:*ejabberd 20.04* 
- **Is your XMPP server working with other clients as expected?*yes*

**Comment by sualko** [comment] 2020-06-24 12:25
duplicate of #873

**Closed by sualko** 2020-06-24 12:25 UTC
