### ISSUE TITLE
Videocall problem

### ISSUE THREAD

**Issue by nasanchez** [jsxc/jsxc#329] opened 2016-04-22 10:36 UTC
I have a problem with videocall. When I do a call for the first time, It works perfectly but when I hangup the call and try to do another call and my contact accepts the call, it falls down and show this error on my chat: Call terminated: jingle_reason_undefined.

**Comment by sualko** [comment] 2016-04-25 10:28
Maybe a duplicate of #294? Please test the fix or try to reload your page.

**Comment by nasanchez** [comment] 2016-04-25 10:50
I'm sorry but I can't find the fix...Where is it?

**Comment by sualko** [comment] 2016-04-25 10:53
Easiest way would be to reload your page, before you call an other person. Otherwise you have to add <code>$(document).off('cleanup.dialog.jsxc');</code> in the <code>hangUp</code> method, but I had no time to add and test it yet.

**Comment by nasanchez** [comment] 2016-04-27 10:00
I tried to add `$(document).off('cleanup.dialog.jsxc'); ` but my problem persists

**Comment by sualko** [comment] 2016-05-02 08:49
Does a page reload fix your issue?

**Comment by nasanchez** [comment] 2016-05-02 08:57
If I reload the page manually all it's ok, but I don't like to do this because the effect to the user is ugly and if the user has a slow connection it could be a little problem because the page could reload slowly.

Reloading the page is the only way to resolve this?

**Comment by sualko** [comment] 2016-05-02 09:01
No, the fix is in #294. I guess you use the minified version, or inserted the snippet to the wrong file. Please wait for the next bug fix release.

**Closed by sualko** 2016-05-02 09:01 UTC
