### ISSUE TITLE
File transfer - no Access-Control-Allow-Origin header 

### ISSUE THREAD

**Issue by smilexcasper** [jsxc/jsxc#529] opened 2017-05-17 12:07 UTC
Which jsxc version number do you use?

    last version

Which browser and browser version do you use?

    Firefox 53.0.2

Do you have any browser plugins enabled?

    firebug

Do you see any errors in your javascript console?
 

> XMLHttpRequest cannot load https://192.168.1.200:5443/upload/5627c20b7457729e75b7a9bebf297dfa7d641042/DEcAUCpmlfBGDjuaHvQzlvHhSff43JjNPy4ugJHD/chat.txt. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.1.200' is therefore not allowed access.

Config:
port: 5443
    module: ejabberd_http
    tls: true
    certfile: 'CERTFILE'
    request_handlers:     
      "": mod_http_upload     

  mod_http_upload:
    docroot: "/var/www"
    put_url: "https://192.168.1.200:5443/upload"
    custom_headers:
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "OPTIONS, HEAD, GET, PUT"

**Comment by sualko** [comment] 2017-05-17 12:09
duplicate of #527

**Comment by smilexcasper** [comment] 2017-05-17 12:10
what??custom error!

**Comment by sualko** [comment] 2017-05-17 12:12
You are right, sorry to closing it to early. Please check https://github.com/jsxc/jsxc/wiki/File-transfer for an explanation of this error.

**Comment by smilexcasper** [comment] 2017-05-17 12:12
if u open - close close 530

**Comment by smilexcasper** [comment] 2017-05-17 12:13
Well, if you look at the configuration - it is the same as https://github.com/jsxc/jsxc/wiki/File-transfer

**Closed by sualko** 2017-05-17 12:12 UTC
Labels: duplicate

**Comment by sualko** [comment] 2017-05-17 12:19
This was the first result on startpage: https://github.com/processone/ejabberd/issues/1482
