### ISSUE TITLE
404 @ /apps/ojsxc/ajax/externalApi.php

### ISSUE THREAD

**Issue by Failure404** [jsxc/jsxc#1012] opened 2021-01-18 16:39 UTC
Hi,
I don't really know when this started, possibly after I upgraded to NC20.
Using my own Prosody together with Xcauth and Nextcloud behind a nginx proxy, when I try to login with JSXC in Nextcloud, Nextcloud returns a 404 for https://mydomain.org/apps/ojsxc/ajax/externalApi.php and login fails.
It used to work fine for many months and I haven't changed anything except upgrading NC whenever there was a new release.
Could someone give me a hint where I could start troubleshooting?

**Comment by sualko** [comment] 2021-01-19 13:44
Please increase your log level and fill the [issue template](https://github.com/jsxc/jsxc/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by Failure404** [comment] 2021-01-19 17:17
I've found the problem.
I am using "pretty links" in NC, where index.php is removed from the URL. This never was a problem, but since recently, index.php is required in the path /index.php/apps/ojsxc/ajax/externalApi.php .
OJSXC still shows in Admin settings "API URL https://mydomain.org/apps/ojsxc/ajax/externalApi.php" but that will not work without index.php in the path.
After modifying the API URL in xcauth.conf, everything works again.
Thanks for reading.

**Comment by sualko** [comment] 2021-01-20 08:14
Thanks for debugging this. I reopen the issue until it is fixed.

**Comment by sualko** [comment] 2021-04-09 12:34
I can't reproduce this issue and therefore I close it.

**Closed by sualko** 2021-04-09 12:34 UTC
Labels: bug, nextcloud
