### ISSUE TITLE
Private groups for contacts

### ISSUE THREAD

**Issue by ostasevych** [jsxc/jsxc#877] opened 2020-04-19 13:59 UTC
**Is your feature request related to a problem? Please describe.**
I cannot easily find the contacts of my colleagues,friends or family members.

**Is your feature request related to a specific XEP?**
tbc

**Describe the solution you'd like**
Please, add group classification in order to group the contacts: favourite (with *) and own groups, eg, family, colleagues, friends etc. which you may create yourself. Each contact may be assigned to more than 1 group.

**Additional context**
It will be good to have ability to contact with group members by text, and audio/video in future.

**Comment by sualko** [comment] 2020-04-20 06:26
Duplicate of #77

**Comment by sualko** [comment] 2020-04-20 06:26
Do you have a proposal for an UI concept? That's the biggest issue for me.

**Closed by sualko** 2020-04-20 06:26 UTC
Labels: duplicate, enhancement

**Comment by ostasevych** [comment] 2020-04-20 12:34
> Do you have a proposal for an UI concept? That's the biggest issue for me.

I will think about it more thorough, the first idea is to use Skype's approach: 

1. To add **Recent** category on top, which may contain recently contacted people and channels (mucs) be (un)collapsed.
2. To add **Favourite** category, placed under **Recent**: this category may contain starred contacts and channels (mucs), which may be (un)collapsed as well
3. In case of shared roster to add **Team** category with the contacts of shared roster, placed under **Favourite**, also to be able to (un)collapse.
4. To place custom named categories, placed lower.
5. To add a 3dots menu icon on the right of the name of a custom created group with the options to hide/rename/delete this group.
6. To add an option to the sandwich menu of a user:
- to add new group.
- to hide/show hidden groups.
7. I also suggest to place a search window above all groups through which a user may look across the names of contacts and groups, as well as the texts of chats eg:
![image](https://user-images.githubusercontent.com/5199030/79751964-2ae20580-831c-11ea-828a-3b142a609f2d.png)
