### ISSUE TITLE
broken if usernames contain spaces

### ISSUE THREAD

**Issue by mejo-** [jsxc/jsxc#570] opened 2017-06-29 10:54 UTC
Hello,

Latest OJSXC on Nextcloud with `xmpp-cloud-auth` and Prosody has a problem if the usernames contain spaces. That's particularly annoying as Nextcloud itself allows spaces in usernames.

Prosody 'mod_bosh' logs:

```
Jun 29 12:50:43 mod_bosh	debug	BOSH body open (sid: 53ef988b-a6c2-4369-8ecd-635b563f613f)
Jun 29 12:50:43 mod_bosh	debug	BOSH stanza received: <auth mechanism='PLAIN' xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>

Jun 29 12:50:43 bosh53ef988b-a6c2-4369-8ecd-635b563f613f	debug	Received[c2s_unauthed]: <auth mechanism='PLAIN' xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
Jun 29 12:50:43 host.example.org:saslauth	debug	sasl reply: <failure xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><malformed-request/><text>Invalid username or password.</text></failure>
```

**Comment by sualko** [comment] 2017-06-29 11:11
duplicate of #501

**Closed by sualko** 2017-06-29 11:11 UTC
