### ISSUE TITLE
Blank video

### ISSUE THREAD

**Issue by bcnx** [jsxc/jsxc#287] opened 2016-03-03 11:06 UTC
Hi,

configuration is a Prosody server with a public IP. The clients are behind a NAT device. The webcams get activated successfully, however the image is black/blank on both clients. I did not find any settings for STUN or TURN servers. Should this be a NAT issue, what needs to happen to support the NATted architecture?

Cheers,

BC

**Comment by shikka** [comment] 2016-03-03 17:15
Hi,

you can try this:
https://github.com/jsxc/jsxc/issues/281

**Comment by bcnx** [comment] 2016-03-03 18:14
I saw that issue but the lines mentioned are not present in the latest version of JSXC,

 
 
Met Vriendelijke Groet,
Kind Regards,
Salutations,
 
 
Bart Coninckx
Bits 'n Tricks BVBA
 
Hoge Mierdse Heide 182
2360 Oud-Turnhout
tel. +32 478 88 33 08
info@bitsandtricks.com
http://www.bitsandtricks.com
BTW: BE0817.401.875

Crelan BE46 8601 0806 3436

Voor onze Algemene Voorwaarden, zie: http://www.bitsandtricks.com/index.php/contact/algemene-voorwaarden

 

 
-----Original message-----

**Comment by bcnx** [comment] 2016-03-03 18:17
This is what I get in the console on the receiving end of a video call. I cannot really make anything of it, but you guys might:

mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create jsxc.dep.js:8371:3
New connection jsxc.min.js:14:1701
CONNECTING: null jsxc.min.js:14:1701
CONNECTED: null jsxc.min.js:14:1701
close dialog jsxc.min.js:14:1701
I am master. jsxc.min.js:14:1701
DSA key loaded jsxc.min.js:14:1701
Load bookmarks from pubsub jsxc.min.js:14:1701
Roster loaded jsxc.min.js:14:1701
create bookmark node jsxc.min.js:14:1701
Presence (bj@dafra.bnt.solutions/jitsi-1llfppt): 5 jsxc.min.js:14:1701
Presence (bc@dafra.bnt.solutions/Dafra): 5 jsxc.min.js:14:1701
Presence (77@dafra.bnt.solutions): 0 jsxc.min.js:14:1701
webrtc.initWindow jsxc.min.js:14:1701
navigator.mozGetUserMedia is vervangen door navigator.mediaDevices.getUserMedia jsxc.dep.js:20221:11
onUserMediaSuccess jsxc.min.js:14:1701
media ready jsxc.min.js:14:1701
close dialog jsxc.min.js:14:1701
using audio device "" jsxc.min.js:14:1701
using video device "" jsxc.min.js:14:1701
WebRTC-interfaces met de ‘moz’-prefix (mozRTCPeerConnection, mozRTCSessionDescription, mozRTCIceCandidate) worden niet meer ondersteund. jsxc.dep.js:20153:11
Mandatory/optional in createOffer options no longer works! Use {"offerToReceiveAudio":true,"offerToReceiveVideo":true} instead (note the case difference)! <onbekend>
incoming call from bc@dafra.bnt.solutions/Dafra jsxc.min.js:14:1701
d-h commit message jsxc.dep.js:37075:7
instance tags jsxc.dep.js:37075:7
reveal signature message jsxc.dep.js:37075:7
instance tags jsxc.dep.js:37075:7
data message jsxc.dep.js:37075:7
success jsxc.dep.js:37075:7
console.trace(): jsxc.dep.js:1978
Strophe.Handler.prototype.run() jsxc.dep.js:1978
Strophe.Connection.prototype._dataRecv/<() jsxc.dep.js:3067
Strophe.forEachChild() jsxc.dep.js:950
Strophe.Connection.prototype._dataRecv() jsxc.dep.js:3055
Strophe.Bosh.prototype._onRequestStateChange() jsxc.dep.js:4699
 
function ()  - error -  TypeError: error is undefined
Stacktrace:
jsxc.webrtc.startCall/<["finish.mediaready.jsxc"]/<@https://dafra.bnt.solutions/build/jsxc.min.js:18:14004
.on/d@https://dafra.bnt.solutions/build/lib/jquery.min.js:3:10895
n.event.dispatch@https://dafra.bnt.solutions/build/lib/jquery.min.js:3:6352
n.event.add/r.handle@https://dafra.bnt.solutions/build/lib/jquery.min.js:3:3162
n.event.trigger@https://dafra.bnt.solutions/build/lib/jquery.min.js:3:5510
.trigger/<@https://dafra.bnt.solutions/build/lib/jquery.min.js:3:11472
.each@https://dafra.bnt.solutions/build/lib/jquery.min.js:2:2878
n.prototype.each@https://dafra.bnt.solutions/build/lib/jquery.min.js:2:845
.trigger@https://dafra.bnt.solutions/build/lib/jquery.min.js:3:11451
[252]</</<.init/</<@https://dafra.bnt.solutions/build/lib/jsxc.dep.js:31991:16
[53]</WildEmitter.mixin/prototype.emit@https://dafra.bnt.solutions/build/lib/jsxc.dep.js:16428:17
[29]</SessionManager.prototype._log@https://dafra.bnt.solutions/build/lib/jsxc.dep.js:14152:5
[29]</SessionManager.prototype.process@https://dafra.bnt.solutions/build/lib/jsxc.dep.js:14205:13
[252]</</<.onJingle@https://dafra.bnt.solutions/build/lib/jsxc.dep.js:32021:1
Strophe.Handler.prototype.run@https://dafra.bnt.solutions/build/lib/jsxc.dep.js:1970:22
Strophe.Connection.prototype._dataRecv/<@https://dafra.bnt.solutions/build/lib/jsxc.dep.js:3067:29
Strophe.forEachChild@https://dafra.bnt.solutions/build/lib/jsxc.dep.js:950:17
Strophe.Connection.prototype._dataRecv@https://dafra.bnt.solutions/build/lib/jsxc.dep.js:3055:9
Strophe.Bosh.prototype._onRequestStateChange@https://dafra.bnt.solutions/build/lib/jsxc.dep.js:4699:17
 error is undefined jsxc.dep.js:1979:21

**Comment by bcnx** [comment] 2016-03-03 18:20
I also added a TURN server to the equation, just to exclude any NAT issues, but video remains black/blank,

BC

**Comment by sualko** [comment] 2016-03-06 16:55
You find RTC configs at (jsxc.lib.options.js#L231)[https://github.com/jsxc/jsxc/blob/master/src/jsxc.lib.options.js#L231], but this is terrible to debug. Sometimes you have to capture all traffic and search for errors, but in your case its maybe <code> TypeError: error is undefined</code>. I will check that next week.

**Comment by sualko** [comment] 2016-03-10 11:11
It feels like this is a NAT issue. Can you check in your js console if <code>jsxc.options.get('RTCPeerConfig')</code> contains your RTC config? 

TypeError and turn credentials are fixed with the above commits, maybe you can also test them.

If nothing helps, can your provide a test account for me? Send those credentials to klaus@jsxc.org with subject "Blank video #287". Thanks.

**Comment by bcnx** [comment] 2016-03-10 20:45
I don't seem to get the jsxc.options.get statement, even after enabling debug and reloading the page. 

I will send you an account in order to verify,

 
Met Vriendelijke Groet,
Kind Regards,
Salutations,
 
 
Bart Coninckx
Bits 'n Tricks BVBA
 
Hoge Mierdse Heide 182
2360 Oud-Turnhout
tel. +32 478 88 33 08
info@bitsandtricks.com
http://www.bitsandtricks.com
BTW: BE0817.401.875

Crelan BE46 8601 0806 3436

Voor onze Algemene Voorwaarden, zie: http://www.bitsandtricks.com/index.php/contact/algemene-voorwaarden

 

 
-----Original message-----

**Comment by sualko** [comment] 2016-03-10 22:19
Ok, I could reproduce your issue. There is a <code>display:none</code> for <code>.jsxc_videoContainer</code>, but currently I don't know why. On my personal installation this is not the case. But this has to wait until tomorrow ;-).

**Comment by bcnx** [comment] 2016-03-11 11:12
Hi,

 
Thank you. I can't find this CSS property in the page code as well. Looking forward to your findings tomorrow,

 
Met Vriendelijke Groet,
Kind Regards,
Salutations,
 
 
Bart Coninckx
Bits 'n Tricks BVBA
 
Hoge Mierdse Heide 182
2360 Oud-Turnhout
tel. +32 478 88 33 08
info@bitsandtricks.com
http://www.bitsandtricks.com
BTW: BE0817.401.875

Crelan BE46 8601 0806 3436

Voor onze Algemene Voorwaarden, zie: http://www.bitsandtricks.com/index.php/contact/algemene-voorwaarden

 

 
-----Original message-----

**Comment by sualko** [comment] 2016-03-11 11:21
I found it. Stupid bug. I was testing only in owncloud and there they use an old version of jquery. In newer versions <code>toggle</code> as click handler is deprecated and hides/shows only elements. So in the end @shikka was right and therefore this is a duplicate of #281.

**Comment by bcnx** [comment] 2016-03-11 11:22
I found this code, it is in the "build" directory, which is on the same level as the jsxc web directory. Commenting the display:none line did not help however. Let's continue this tomorrow, 

 
Met Vriendelijke Groet,
Kind Regards,
Salutations,
 
 
Bart Coninckx
Bits 'n Tricks BVBA
 
Hoge Mierdse Heide 182
2360 Oud-Turnhout
tel. +32 478 88 33 08
info@bitsandtricks.com
http://www.bitsandtricks.com
BTW: BE0817.401.875

Crelan BE46 8601 0806 3436

Voor onze Algemene Voorwaarden, zie: http://www.bitsandtricks.com/index.php/contact/algemene-voorwaarden

 

 
-----Original message-----

**Closed by sualko** 2016-03-11 11:21 UTC

**Comment by bcnx** [comment] 2016-03-11 12:17
I commented the code referred to in #281 out, but I still get a black/blank screen for the video card. Audio seems to be OK. Would you mind testing on my system again?

 
Thanks,

 
Met Vriendelijke Groet,
Kind Regards,
Salutations,
 
 
Bart Coninckx
Bits 'n Tricks BVBA
 
Hoge Mierdse Heide 182
2360 Oud-Turnhout
tel. +32 478 88 33 08
info@bitsandtricks.com
http://www.bitsandtricks.com
BTW: BE0817.401.875

Crelan BE46 8601 0806 3436

Voor onze Algemene Voorwaarden, zie: http://www.bitsandtricks.com/index.php/contact/algemene-voorwaarden

 

 
-----Original message-----

**Comment by bcnx** [comment] 2016-03-11 12:36
I tried with and without STUN server and audio functions in both directions, so this does not seem to be a NAT issue (or other NAT rules apply to video sharing). 

 
Met Vriendelijke Groet,
Kind Regards,
Salutations,
 
 
Bart Coninckx
Bits 'n Tricks BVBA
 
Hoge Mierdse Heide 182
2360 Oud-Turnhout
tel. +32 478 88 33 08
info@bitsandtricks.com
http://www.bitsandtricks.com
BTW: BE0817.401.875

Crelan BE46 8601 0806 3436

Voor onze Algemene Voorwaarden, zie: http://www.bitsandtricks.com/index.php/contact/algemene-voorwaarden

 

 
-----Original message-----

**Comment by sualko** [comment] 2016-03-11 13:05
Please do not quote the original message, because it is a mess on github.

Maybe you could test the fix from d556d74.

**Comment by bcnx** [comment] 2016-03-11 13:11
Klaus,

 
I'm sorry, I wasn't aware of this.

I did a new git clone and I just discovered that I still get a display:none for jsxc_videoContainer . If I remove it in the browser console, the video images are functional (that is, on my Windows, on my Mac I 'don't se the video of the Windows party - but that is probably another issue, will create an issue for that if needed)

 
I will try the fix you suggest now and will report in a minute. 

 
Thanks for your patience,

 
Met Vriendelijke Groet,
Kind Regards,
Salutations,
 
 
Bart Coninckx
Bits 'n Tricks BVBA
 
Hoge Mierdse Heide 182
2360 Oud-Turnhout
tel. +32 478 88 33 08
info@bitsandtricks.com
http://www.bitsandtricks.com
BTW: BE0817.401.875

Crelan BE46 8601 0806 3436

Voor onze Algemene Voorwaarden, zie: http://www.bitsandtricks.com/index.php/contact/algemene-voorwaarden

**Comment by bcnx** [comment] 2016-03-11 13:28
Hi,

 
up till now I installed JSXC by copying the example and the build folder to my Apache directory (which seems to do the same thing as the install instruction of the WIKI). I'm not quite understanding the page you sent with the differences in the code. They seem to expect some sort of compilation of the source code (which is not referred to by the WIKI install instructions. How should I apply these diffs ?

 
Cheers,

 
Met Vriendelijke Groet,
Kind Regards,
Salutations,
 
 
Bart Coninckx
Bits 'n Tricks BVBA
 
Hoge Mierdse Heide 182
2360 Oud-Turnhout
tel. +32 478 88 33 08
info@bitsandtricks.com
http://www.bitsandtricks.com
BTW: BE0817.401.875

Crelan BE46 8601 0806 3436

Voor onze Algemene Voorwaarden, zie: http://www.bitsandtricks.com/index.php/contact/algemene-voorwaarden

**Comment by sualko** [comment] 2016-03-11 13:36
Just remove the following lines: https://github.com/jsxc/jsxc/blob/91f8c5a2f170a664999dac026d3caebe5106f4c5/build/jsxc.js#L9932-L9936 or wait for the final release of 3.0 ;-).

To install a developer environment would be a little bit over the top.

**Comment by bcnx** [comment] 2016-03-11 13:56
Hi Klaus,

 
thank you for your patience. I tried that before (before replacing them with the other code) and the video is still black with "style="display: none;" active for the the container. It seems the DIV is not affected by the lines I deleted. 

 
Met Vriendelijke Groet,
Kind Regards,
Salutations,
 
 
Bart Coninckx
Bits 'n Tricks BVBA
 
Hoge Mierdse Heide 182
2360 Oud-Turnhout
tel. +32 478 88 33 08
info@bitsandtricks.com
http://www.bitsandtricks.com
BTW: BE0817.401.875

Crelan BE46 8601 0806 3436

Voor onze Algemene Voorwaarden, zie: http://www.bitsandtricks.com/index.php/contact/algemene-voorwaarden

**Comment by sualko** [comment] 2016-03-11 14:00
You have to use the unminified version in index.html. Just change the line
```
<script src="../build/jsxc.min.js"></script>
```
to 
```
<script src="../build/jsxc.js"></script>
```
Do not forget to do a hard reload.

**Comment by bcnx** [comment] 2016-03-11 14:20
That makes a difference, I see myself for a second but as soon as I pick up the call and allow selection of webcam and micro, the call ends and the video screen is gone at the caller's end. Not an easy delivery ... 

 
 
Met Vriendelijke Groet,
Kind Regards,
Salutations,
 
 
Bart Coninckx
Bits 'n Tricks BVBA
 
Hoge Mierdse Heide 182
2360 Oud-Turnhout
tel. +32 478 88 33 08
info@bitsandtricks.com
http://www.bitsandtricks.com
BTW: BE0817.401.875

Crelan BE46 8601 0806 3436

Voor onze Algemene Voorwaarden, zie: http://www.bitsandtricks.com/index.php/contact/algemene-voorwaarden

**Comment by bcnx** [comment] 2016-03-11 14:33
Different browser works, so different issue. I will do some intensive testing to see what works and what does not.

Thank you again for your time and patience. This is a neat chat client.

 
 
Met Vriendelijke Groet,
Kind Regards,
Salutations,
 
 
Bart Coninckx
Bits 'n Tricks BVBA
 
Hoge Mierdse Heide 182
2360 Oud-Turnhout
tel. +32 478 88 33 08
info@bitsandtricks.com
http://www.bitsandtricks.com
BTW: BE0817.401.875

Crelan BE46 8601 0806 3436

Voor onze Algemene Voorwaarden, zie: http://www.bitsandtricks.com/index.php/contact/algemene-voorwaarden

**Comment by tristan-k** [comment] 2016-05-13 14:23
I'm also struggeling with this issue.
