### ISSUE TITLE
Message Archive Management (XEP-0313)

### ISSUE THREAD

**Issue by fuesschen** [jsxc/jsxc#315] opened 2016-04-06 20:46 UTC
Message Archive Management syncs the conversations from and to the server. 

[XEP-0313](http://xmpp.org/extensions/xep-0313.html)

**Comment by v1r0x** [comment] 2016-04-08 10:04
duplicate of #150 ;)

**Comment by sualko** [comment] 2016-04-08 10:09
Thanks @v1r0x

**Closed by sualko** 2016-04-08 10:09 UTC
Labels: duplicate, enhancement
