### ISSUE TITLE
Bad time-based ordering of old messages in a muc

### ISSUE THREAD

**Issue by mmoqui** [jsxc/jsxc#738] opened 2018-10-25 09:12 UTC
We use JSXC 3.4.2 as the backbone of our own messaging client (https://github.com/Silverpeas/silverchat). In this client, the JSXC chat windows aren't touched and are used as such. In this client, rooms are automatically created and registered in the XMPP server (ejabberd) when a user open a talk with more than one user in its roster. (The room then appeared in the roster of each of the users). Such rooms are commonly used with 5 or more users.

We remarked from the beginning that in some circumstances, when a room window is opened, the previous messages aren't correctly ordered in time and some of our own messages are marked as coming from other users (background in blue instead of green).

First we thank the problem was coming from the message logging in JSXC. We then set the option `numberOfMsg` to 0 and kept enable only the MAM. But the problem isn't off :-(

Do you have experienced such a problem? Any idea about the problem?

**Comment by sualko** [comment] 2018-10-25 10:46
So your problem is that existing and MAM messages get mixed. I'm I right? If this is the case we discovered this behavior earlier and named it MAM synchronization. We try to implement this in 4.0, but probably it will be in 4.1. The problem is that not all clients add a stanza id to there messages, so we have to use some kind of heuristic to guess if it's the same message. If you like to work on this, I can give you some hints and a starting point.

**Comment by mmoqui** [comment] 2018-10-26 08:04
Indeed, the first time we encountered the problem was with the messages logging and the MAM both enabled. Because I thought the problem could come from the mixture of both the local history of JSXC and MAM I disabled the messages logging in JSXC to keep only MAM. In our case, we use only JSXC as XMPP client (no other XMPP/Jabber client).

The problem occurs when just opening the first time of the day a room window. To easily reproduce the problem:
The context: the messages logging in JSXC is disabled by setting `numberOfMsg` to 0. The MAM is enabled both in ejabberd and JSXC (with `mam.max = 100` in JSXC). The only client used is JSXC.
- Disconnection with ejabberd in JSXC
- Clear the web browser cache (check the local and global storage are well emptied) to ensure any history of messages are swept out.
- Connection to ejabberd in JSXC
- Open an existing room with at least 4 or 5 registered users (no tested under that number) from the roster
=> some of the previous messages aren't correctly ordered in the time and my previous messages are displayed as coming from another user. In this case, normally, the previous messages should come only from MAM.

(Note: some users like me have an option in the web browser to automatically clean up all the data (cache/cookies/storage) wen closing the browser.)

**Comment by sualko** [comment] 2018-10-26 13:59
I currently see 2 issues:

1. "some of the previous messages aren't correctly ordered in the time"
2. "my previous messages are displayed as coming from another user"

Remarks to the first one: Can you explain this in more detail? Are they totally messed up, or are blocks of messages correctly ordered? Because the order is predefined from the server.

The second one is even more trickier: There is no guarantee that those messages are from you, because during the join everyone can choose there nickname by there one. So it would be misleading if we display those messages like they are from you. @danscharon Do you have a solution for this?

**Comment by DanScharon** [comment] 2018-10-26 14:32
If MAM doesn't store the real JID but only the nicknames within MUCs it gets really tricky. If we would display those messages as coming from you it should at least be in a way that admits that it actually may have not come from you.

**Comment by mmoqui** [comment] 2018-10-31 08:42
@sualko More information after different tests about 1.
- What is reproducible: you have a room chat window opened. You write a message in this room, then explicitly you do in JSXC  a disconnection following by a connection: the room window is showed and your last message is displayed as being your but before all the previous messages instead of being displayed after all others because the newer. (It is like to be saved in the history whereas numberOfMsg = 0)
- What it is no reproducible: some times, with a lot of messages, the last ones of mine are "in the middle" of the previous exchanged messages!

For 2. Doesn't the bid be part of the messages fetched from the mam?

**Comment by mmoqui** [comment] 2018-10-31 15:59
I tried to understand how jsxc works with mam by following its execution flow in the Chrome's debugger. What I don't understand is that when opening a chat room window, the previous messages are displayed within it but the functions `jsxc.xmpp.mam.onMessage` or `jsxc.xmpp.mam.onComplete` are never invoked. Even whether I clear the browser's caches (local and global storages + cookies) before, once connected and a chat room window opened, the previous messages are here whereas the mam functions onMessage and onComplete aren't invoked; so those messages cannot come from the storage, but then from where?

**Comment by mmoqui** [comment] 2018-11-05 14:06
After some investigations, I found that existing messages are displayed into the room chat window by the jsxc.muc.onGroupChatMessage function. What I don't know for instance is from where those message come  and what invokes this function (it seams it is referred as a handler by jsxc.muc.onGroupchatMessageHandlerRef but a handler of what?)

In this function, all the existing messages are rendered by calling jsxc.gui.window.postMessage. The messages are rebuilt but with jsxc.Message.IN as direction. And I think this is why the messages of the user are displayed as coming from another one; indeed, by inspecting the HTML element of a message, the css class to distinguish a message of mine from the others is giving by the css class jxc_out (jsxc_in for messages coming from others users).

**Comment by mmoqui** [comment] 2018-11-09 17:58
For the problem coming from the rendering of messages when a room window is opened, I propose a fix through the PR https://github.com/jsxc/jsxc/pull/742.

**Comment by sualko** [comment] 2018-11-19 14:06
Kann you test d62604a? As I said above, we can only associate nicknames and jids if we receive an "live" message. Because if we join a room we get a list of jids and nicknames of the current members, but we don't know if in the history some other members used that nickname. Therefore my commit will make this association only for message which arrive after we joined.

I guess you still have trouble with the message reordering? Is that right?

**Comment by mmoqui** [comment] 2018-11-20 11:20
I just ended to test d62604a. And in my tests, your work ... works fine ;-)

For the message reordering, yes I have again some trouble. Nevertheless, I succeeded to figure out how to reproduce it:
- write a message into a groupchat
- disconnect immediately or a short time after writing that message
- reconnect again
- the message appears atop of the older ones instead of being rendered at the last one (at the bottom). In some circumstances, with MAM (fetching of older messages) this message can be rendered in the middle.

What I think to understand is that when jsxc opens a connection to the XMPP server, for each rooms bookmarked in the roster of the current user it joins that room automatically and this works like the user is joining for the first time the room: the server sent back a set of previous existing messages, the groupchat window is automatically opened with the received messages. Doesn't XMPP have just an entrance operation to an already joined room? (In my mind, joined means subscribed)

**Comment by sualko** [comment] 2018-11-28 12:52
I looked at it, and I maybe think I now know what is going on there, even if I can't reproduce it. The message history is not provided by MAM but rather by MUC itself. I guess it's a timing issue and therefore it doesn't occur all the time. It would be great if you could test this with the upcoming [JSXC 4.0](https://www.jsxc.org/blog/2018/09/26/v4.0.0-first-alpha-released.html), because I think it's to big to fix it in 3.x.

**Closed by sualko** 2018-11-28 12:52 UTC
Labels: bug

**Comment by mmoqui** [comment] 2018-12-05 09:59
Hi, ok, I will test this with the next major version of jsxc. I don't know when because currently I'm very busied.
