### ISSUE TITLE
TypeError: req is undefined

### ISSUE THREAD

**Issue by devendrawebdeveloper** [jsxc/jsxc#358] opened 2016-08-08 07:02 UTC
![oie_1q3l3ay8f1x5](https://cloud.githubusercontent.com/assets/4918366/17471782/35d2cd08-5d64-11e6-8185-c86df0a953ba.png)

**Comment by devendrawebdeveloper** [comment] 2016-08-08 09:40
I found solution it is conflict with mootools.
Can you provide some solution?
When I did remove mootools-more.js and mootools-core.js then it is work but login user show offline in openfire.

**Comment by devendrawebdeveloper** [comment] 2016-08-09 11:50
Can you reply on that please?

**Comment by sualko** [comment] 2016-08-10 05:40
I found the following post on [stackoverflow](http://stackoverflow.com/questions/19357292/strophejs-conflict-with-mootools), maybe it is helpful. Otherwise try to wrap the jsxc init code and use jquery noconflict mode, similar to [this post](http://stackoverflow.com/questions/2810399/jquery-and-mootools-conflict#answer-2810523).

**Comment by devendrawebdeveloper** [comment] 2016-08-10 05:49
Okay I will try now.
Also Can you explain following points?
1)  it is not working with jquery 1.7.1 .
2) Chat is not save longer it is showing 11 msg but i have already change option 10 to 100,But How can we archive chat?

**Comment by skyfox675** [comment] 2016-08-10 11:08
@devendrawebdeveloper, your going to need an XMPP server compatible with XEP-0313 MAM message archive management. If the messages are sent thru jsxc the history may not queryable until the client can support MAM,  though it will still be logged by your server and can be quieried by another client such as gajim for windows with the MAM plug in.

**Comment by devendrawebdeveloper** [comment] 2016-08-10 11:11
Okay but I have installed Monitoring Service plugin in openfire but it is not store in database.

**Comment by skyfox675** [comment] 2016-08-10 11:22
Personally, I haven't gotten the Monitoring service plugin to work as MAM, if I remember correctly, it is not XEP-0313 compliant, but functions in a similar way.

**Comment by devendrawebdeveloper** [comment] 2016-08-10 11:28
I am really new.Not understand what we do in it.
Can you just give me instruction How can we set that?

**Comment by skyfox675** [comment] 2016-08-10 12:07
Looks like this might provide some help:
https://community.spiceworks.com/topic/228394-how-do-i-monitor-conversations-in-openfire-chat

As per this link it looks like the most recent version 1.4.6 of the monitoring service plugin does support MAM, https://community.igniterealtime.org/thread/57111

Wish I could provide more answers but I am no longer running Openfire and have switched to Ejabberd.

**Comment by devendrawebdeveloper** [comment] 2016-08-10 18:08
Is Ejabberd 16.06 or Openfire good work with jsxc?
Like all MSG and file share etc.

**Comment by skyfox675** [comment] 2016-08-10 18:10
Ejabberd 16.06 I can say works very well, file transfer is ok if you use HTTP-Upload, will result in the recipient receiving a link to the media instead of the media itself which is a bit faster.

Overall I would recommend it.

**Comment by devendrawebdeveloper** [comment] 2016-08-11 10:55
I have install Ejabberd But please help to config with jsxc.

**Comment by devendrawebdeveloper** [comment] 2016-08-11 12:46
Okay. I have configured all.But I am facing same issue with Ejabberd.
 Can you explain following points?
1) Chat is not save longer it is showing 11 msg but i have already change option 10 to 100,But How can we archive all chat so user can see after one year or more?

**Comment by skyfox675** [comment] 2016-08-11 12:49
Ejabberd supports MAM by default it will be listed in the modules section of the config. JSXC does not support MAM. If you wish to query old messages, you will have to preform the MAM query via another client such as gajim or pidgen. Nothing is needed to allow MAM archiving within JSXC, though again, you will not be able to retrieve MAM archives via JSXC.

**Comment by sualko** [comment] 2016-10-05 15:34
@devendrawebdeveloper Where did you configure ``numberOfMsg``?

**Comment by devendrawebdeveloper** [comment] 2016-10-06 06:37
in jsxc options, we did change but not working so i used mam for archive data.

**Comment by devendrawebdeveloper** [comment] 2016-10-06 06:39
We was need whole chat.

**Comment by sualko** [comment] 2016-10-06 07:00
As far as your issue is solved and I am unable to reproduce your initialize problem, I close this issue.

**Closed by sualko** 2016-10-06 07:00 UTC
