### ISSUE TITLE
JSXC side bar loads before 2FA is completed (ownCloud)

### ISSUE THREAD

**Issue by madpsy** [jsxc/jsxc#531] opened 2017-05-17 14:46 UTC
Using version 3.1.1 with ownCloud 9.1.4.

When 2FA in ownCloud is enabled, the chat side bar appears (and logs in) straight after the username/password  authentication in ownCloud but before 2FA has completed. This is obviously not ideal.

To reproduce simply enable 2FA in ownCloud and watch the JSXC side chat bar appear before entering your 2FA token.

**Comment by sualko** [comment] 2017-05-18 07:34
duplicate of #436

**Closed by sualko** 2017-05-18 07:34 UTC
Labels: duplicate
