### ISSUE TITLE
Kontaktfilter in Kontaktliste/ Contactfilter in Roster

### ISSUE THREAD

**Issue by mightymop** [jsxc/jsxc#957] opened 2020-12-15 10:43 UTC
**Is your feature request related to a problem? Please describe.**
An Inputfield to filter contacts in roster will be useful. We have rosters with over 500 Users and it is hard to scroll down.

**Is your feature request related to a specific XEP?**
no

**Describe the solution you'd like**
i have added an inputfield with an keyup event to filter the userlist. Maybe it is useful to implement this in the core:

```
 function addContactFilter()
    {
        $(".jsxc-contact-list-wrapper").prepend("<input type='text' id='filterlist' placeholder='Kontaktfilter' />");
        $("#filterlist").off("keyup").on("keyup",function(e)
        {
            var val = $(this).val();
            if (val&&val.length>0)
            {
                val=val.toLowerCase();
                $.each( $(".jsxc-contact-list").children("li"), function( key, value )
                {
                    var text = $(this).children("div.jsxc-bar__caption.jsxc-grow").text().trim().toLowerCase();
                    if (text.indexOf(val)==-1&&$(this).attr("data-id").substring(0,$(this).attr("data-id").indexOf("@")).toLowerCase().indexOf(val)==-1)
                    {
                        $(this).css({"display":"none"});
                    }
                });
            }
            else
            {
                $.each( $(".jsxc-contact-list").children("li"), function( key, value )
                {
                     $(this).css({"display":""});
                });
            }
        });
    }
```

**Comment by sualko** [comment] 2020-12-15 12:48
Thank you for your request. I think it's a duplicate of #932, but since this issues has ah bit more information I close the older issue.

The main issue is the design decision where we should place the filter bar. Do you have an idea?

**Comment by mightymop** [comment] 2020-12-15 13:21
> Thank you for your request. I think it's a duplicate of #932, but since this issues has ah bit more information I close the older issue.
> 
> The main issue is the design decision where we should place the filter bar. Do you have an idea?

I would add the inputfield at top of the roster list... as you can see in the function:
$(".jsxc-contact-list-wrapper").prepend("<input type='text' id='filterlist' placeholder='Kontaktfilter' />");

so you have direct access for it...

**Closed** 2021-01-02 16:12 UTC
Labels: UI, enhancement
