### ISSUE TITLE
Error when enabling jsxc in NC 20.0.1 "Undefined offset: 3 at /var/www/html/lib/private/legacy/OC_Helper.php#548"

### ISSUE THREAD

**Issue by frankbootmaker** [jsxc/jsxc#947] opened 2020-10-28 09:25 UTC
### Expected behavior
The installation and enabling of the application takes place without error

### Actual behavior
The enabling of the application within NC 20.0.1 gets blocked

### Steps to reproduce the behavior
1. Upgrade / install NC 20.0.1 and download and enable the current JSXC application
2.
3.

### Environment
- **JSXC version:** 4.1.1
- **Host system and version:** <NC 20.0.1 docker version>
- **Browser vendor and version:** Chrome, Firefox, Edge
- **Any browser plugins enabled?** No
- **XMPP server vendor and version:** Built-in XMPP
- **Is your XMPP server working with other clients as expected?** N/A - using the built-in XMPP only

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

Error: Undefined offset: 3 at /var/www/html/lib/private/legacy/OC_Helper.php#548

    /var/www/html/lib/private/legacy/OC_Helper.php - line 548:

    OC\Log\ErrorHandler::onError(8, "Undefined offset: 3", "/var/www/ht ... p", 548, { path: "/", ... }})

    /var/www/html/apps/settings/lib/Settings/Personal/PersonalInfo.php - line 108:

    OC_Helper::getStorageInfo("/")

    /var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php - line 141:

    OCA\Settings\Settings\Personal\PersonalInfo->getForm()

    /var/www/html/apps/settings/lib/Controller/PersonalSettingsController.php - line 77:

    OCA\Settings\Controller\PersonalSettingsController->formatSettings({ 10: [ OCA\ ... ]})

    /var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php - line 152:

    OCA\Settings\Controller\PersonalSettingsController->getSettings("personal-info")

    /var/www/html/apps/settings/lib/Controller/PersonalSettingsController.php - line 68:

    OCA\Settings\Controller\PersonalSettingsController->getIndexResponse("personal", "personal-info")

    /var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 169:

    OCA\Settings\Controller\PersonalSettingsController->index("personal-info")

    /var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 100:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings ... {}, "index")

    /var/www/html/lib/private/AppFramework/App.php - line 152:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings ... {}, "index")

    /var/www/html/lib/private/Route/Router.php - line 308:

    OC\AppFramework\App::main("OCA\\Settin ... r", "index", OC\AppFramew ... {}, { section: " ... "})

    /var/www/html/lib/base.php - line 1009:

    OC\Route\Router->match("/settings/user")

    /var/www/html/index.php - line 37:

    OC::handleRequest()

**Comment by DJCrashdummy** [comment] 2020-11-19 11:11
i'm must confirm the behaviour for NC 19 and JavaScript XMPP Chat 4.1.1! :disappointed:

...although JavaScript XMPP Chat 4.1.1 workes fine with NC 18.

**Comment by sualko** [comment] 2020-12-04 09:55
I'm sorry, but I can't reproduce your issue. Neither in 19 or 20. Can you try to provide more information? Like php version, is it a fresh installation, and so on. In the error log I also don't see any relation to jsxc.

**Comment by frankbootmaker** [comment] 2020-12-07 17:50
Hi, sorry as I think I was pasting earlier wrong log segment.
The one I have during the enabling of the XMPP chat is:


Error | index | Exception: XMLWriter::writeAttribute() expects parameter 2 to be string, null given/var/www/html/lib/private/AppFramework/App.php - line 152: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings ... {}, "enableApps")/var/www/html/lib/private/Route/Router.php - line 308: OC\AppFramework\App::main("OCA\\Settin ... r", "enableApps", OC\AppFramew ... {}, { action: nu ... "})/var/www/html/lib/base.php - line 1008: OC\Route\Router->match("/settings/apps/enable")/var/www/html/index.php - line 37: OC::handleRequest()Okozta:TypeError: XMLWriter::writeAttribute() expects parameter 2 to be string, null given/var/www/html/3rdparty/sabre/xml/lib/Writer.php - line 229: XMLWriter->writeAttribute("name", null)/var/www/html/3rdparty/sabre/xml/lib/Writer.php - line 209: Sabre\Xml\Writer->writeAttribute("name", null)/var/www/html/3rdparty/sabre/xml/lib/Serializer/functions.php - line 176: Sabre\Xml\Writer->writeAttributes({ jid: "Test ... "})/var/www/html/3rdparty/sabre/xml/lib/Writer.php - line 101: Sabre\Xml\Serializer\standardSerializer(Sabre\Xml\Wr ... ]}, "")/var/www/html/3rdparty/sabre/xml/lib/Serializer/functions.php - line 177: Sabre\Xml\Writer->write({ name: "ite ... "})/var/www/html/3rdparty/sabre/xml/lib/Serializer/functions.php - line 184: Sabre\Xml\Serializer\standardSerializer(Sabre\Xml\Wr ... ]}, { name: "ite ... "})/var/www/html/3rdparty/sabre/xml/lib/Writer.php - line 101: Sabre\Xml\Serializer\standardSerializer(Sabre\Xml\Wr ... ]}, [ { name: "q ... }])/var/www/html/3rdparty/sabre/xml/lib/Serializer/functions.php - line 177: Sabre\Xml\Writer->write([ { name: "q ... }])/var/www/html/3rdparty/sabre/xml/lib/Serializer/functions.php - line 184: Sabre\Xml\Serializer\standardSerializer(Sabre\Xml\Wr ... ]}, [ { name: "q ... }])/var/www/html/3rdparty/sabre/xml/lib/Writer.php - line 101: Sabre\Xml\Serializer\standardSerializer(Sabre\Xml\Wr ... ]}, [ { name: "i ... }])/var/www/html/custom_apps/ojsxc/lib/db/iqrosterpush.php - line 79: Sabre\Xml\Writer->write([ { name: "i ... }])/var/www/html/3rdparty/sabre/xml/lib/Serializer/functions.php - line 160: OCA\OJSXC\Db\IQRosterPush->xmlSerialize(Sabre\Xml\Wr ... ]})/var/www/html/3rdparty/sabre/xml/lib/Writer.php - line 101: Sabre\Xml\Serializer\standardSerializer(Sabre\Xml\Wr ... ]}, OCA\OJSXC\Db ... l})/var/www/html/custom_apps/ojsxc/lib/db/stanzamapper.php - line 48: Sabre\Xml\Writer->write(OCA\OJSXC\Db ... l})/var/www/html/custom_apps/ojsxc/lib/rosterpush.php - line 106: OCA\OJSXC\Db\StanzaMapper->insert(OCA\OJSXC\Db ... l})/var/www/html/custom_apps/ojsxc/lib/rosterpush.php - line 151: OCA\OJSXC\RosterPush->removeRosterItem("Testuser")/var/www/html/custom_apps/ojsxc/lib/Migration/RefreshRoster.php - line 69: OCA\OJSXC\RosterPush->refreshRoster()/var/www/html/lib/private/Repair.php - line 106: OCA\OJSXC\Migration\RefreshRoster->run(OC\Repair {})/var/www/html/lib/private/legacy/OC_App.php - line 1042: OC\Repair->run()/var/www/html/lib/private/Installer.php - line 169: OC_App::executeRepairSteps("ojsxc", { step: "OCA ... "})/var/www/html/apps/settings/lib/Controller/AppSettingsController.php - line 448: OC\Installer->installApp("ojsxc")/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 169: OCA\Settings\Controller\AppSettingsController->enableApps([ "ojsxc"], [])/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 100: OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings ... {}, "enableApps")/var/www/html/lib/private/AppFramework/App.php - line 152: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings ... {}, "enableApps")/var/www/html/lib/private/Route/Router.php - line 308: OC\AppFramework\App::main("OCA\\Settin ... r", "enableApps", OC\AppFramew ... {}, { action: nu ... "})/var/www/html/lib/base.php - line 1008: OC\Route\Router->match("/settings/apps/enable")/var/www/html/index.php - line 37: OC::handleRequest()
-- | -- | --


This is now on NC 20.0.2, Docker version with PHP 7.4.12

**Comment by sualko** [comment] 2020-12-07 18:51
I think this is a duplicate of #916. See the linked fix for details.

**Closed by sualko** 2020-12-07 18:51 UTC
Labels: nextcloud

**Comment by frankbootmaker** [comment] 2020-12-07 19:43
Yes, indeed this fixed the issue.

However as this fix is now 5 months old, why was it yet not merged into the version on the nextcloud app store?

Cheers,
Feri

**Comment by sualko** [comment] 2020-12-07 20:58
> However as this fix is now 5 months old, why was it yet not merged into the version on the nextcloud app store?

Because sometime time flies and the paid job is more important.

**Comment by frankbootmaker** [comment] 2020-12-08 07:30
I agree, that is a fair answer! :-)
________________________________

**Comment by Aquariu** [comment] 2020-12-10 14:22
Dear all,

Sorry for asking what may look like a dumb question...
With the fix discussed here, is there any planned release of JSXC Nextcloud app that would be officialy compatible with NC 20?
Kind regards,
Olivier

**Comment by sualko** [comment] 2020-12-10 14:23
There should be a new beta in a few hours and a stable release on the weekend. At least that is the plan.
