### ISSUE TITLE
Archive message not displaying in chatbox But its coming from the server.

### ISSUE THREAD

**Issue by mkjain554** [jsxc/jsxc#653] opened 2017-12-21 10:47 UTC
Expected behavior

Chat archiving functionality coming from backend properly,And render On the chatBox

Actual behavior
Steps to reproduce the behavior

    Clicking on the Load more messages
    2.In network i can see all the message coming from backend is ok and I can can see the xml having all the messages,But when its going to render on the chatbox its misses some messages its happen the same when I am tried again to load.
    3.Conclusion is that some message are not rendering in the chat box.

Environment

    JSXC version: v3.2.1 - 2017-06-01
    Host system and version:
    Browser vendor and version: Chrome(Version 51.0.2704.103 (64-bit))/Firefox
    Any browser plugins enabled: NO
    XMPP server vendor and version: Openfire 4.1.4 (XMPP)
    Is your XMPP server working with other clients as expected?: On android/IOS its working fine they are using some other libraries for chat.

Logs
Javascript

No Errors found in Console

**Comment by sualko** [comment] 2017-12-21 13:13
duplicate of #650

**Closed by sualko** 2017-12-21 13:13 UTC
