### ISSUE TITLE
HTTP Upload fails with managed backend

### ISSUE THREAD

**Issue by sualko** [jsxc/jsxc#654] opened 2017-12-30 20:13 UTC
@MarcelWaldvogel 

Chrome/62.0.3202.97

**Console error message:**
```
Failed to load https://userdata.[DOMAIN].jsxc.ch/f3117686f6c2d7970fae9c263771a59e859cc3fb/YC0Udmaea8LEyqGEtQYYATl7Kl63FKQXbFujk2z5/Dez-2017.md.html: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Origin 'https://[DOMAIN]' is therefore not allowed access.
```

**Request:**
```
Request URL:https://userdata.[DOMAIN].jsxc.ch/f3117686f6c2d7970fae9c263771a59e859cc3fb/YC0Udmaea8LEyqGEtQYYATl7Kl63FKQXbFujk2z5/Dez-2017.md.html
Request Method:OPTIONS
Status Code:200 
Remote Address:193.197.88.169:443
Referrer Policy:no-referrer-when-downgrade
```

**Response header:**
```
access-control-allow-headers:Content-Type
access-control-allow-headers:Content-Type
access-control-allow-methods:OPTIONS, HEAD, GET, PUT
access-control-allow-methods:OPTIONS, HEAD, GET, PUT
access-control-allow-origin:*
access-control-allow-origin:*
content-length:1
content-security-policy:upgrade-insecure-requests
content-type:text/plain
date:Sat, 30 Dec 2017 20:08:59 GMT
server:Apache/2.4.29 (Ubuntu)
status:200
strict-transport-security:max-age=31536000
```

**Comment by poVoq** [comment] 2017-12-31 09:04
It looks like a similar issue I had with my ejabbered installation. I am not 100% what the cause for that is, but moving the custom "access-control-allow" sections from the listen section of the ejabberd.yml to the modul config part under mod_http_upload seems to have fixed it.
The configuration tutorials you can find on the net about it are a bit unclear about how to set that up, as both places are mentioned.

**Comment by MarcelWaldvogel** [comment] 2018-01-03 16:38
Adding them to **both** the *ejabberd* `modules` section **and** "replacing" them in Apache results in dual headers. Weird. Apache `mod_headers` bug? Removed the following lines from the Apache configuration:

```Apache
Header always set Access-Control-Allow-Origin "*"
Header always set Access-Control-Allow-Methods "OPTIONS, HEAD, GET, PUT"
Header always set Access-Control-Allow-Headers "Content-Type"
```

**Comment by koarlmichael** [comment] 2018-01-04 08:42
Between two conversation clients on the android phones, http upload only worked for a short time yesterday. Today I've tried again in the nextcloud chat, but http upload does not work anyway. The message comes: connection to the server lost

**Comment by MarcelWaldvogel** [comment] 2018-01-04 16:19
Sorry for the issue. Need to refactor some code anyway; I hope to clean up the mess that was caused when we ran out of Let's Encrypt certificates (and an alternative hack had to be put into place).

**Comment by MarcelWaldvogel** [comment] 2018-01-08 08:08
Sorry for the issue. Need to refactor some code anyway; I hope to clean up the mess that was caused when we ran out of Let's Encrypt certificates (and an alternative hack had to be put into place).

**Comment by MarcelWaldvogel** [comment] 2018-01-24 16:00
Sorry, cannot reproduce this. If you can, could you please provide additional information?

**Comment by koarlmichael** [comment] 2018-01-24 17:29
The problem should now be solved. http upload between two android phones with conversation as a client and with OMEMO encryption works flawlessly. http upload in Nextcloud with the browser also works (without OMEMO). Groupchat with OMEMO (conversation Android) is still not possible. Thanks for the fix!

**Comment by MarcelWaldvogel** [comment] 2018-01-24 17:42
Do you know whether this is related to the OMEMO changes in ejabberd 17.12? We are not running that yet, but hopefully will upgrade soon (or skip to 18.01, as we had trouble with 17.12).

**Comment by koarlmichael** [comment] 2018-01-24 21:06
I'm testing the group chat with OMEMO again tomorrow. Do not think it's on the server.

**Comment by koarlmichael** [comment] 2018-01-25 19:48
Tried it with 3 users with OMEMO encryption in the group chat and it works perfectly with Conversation on Android. Just wait for OMEMO in Nextcloud Chat in the Browser :) Thank you and I think you can close the issue.

**Closed** 2018-01-29 15:01 UTC
Labels: bug, managed-backend
