### ISSUE TITLE
Password change - XMPP doesn't work anymore

### ISSUE THREAD

**Issue by beccon4** [jsxc/jsxc#179] opened 2015-05-27 18:07 UTC
When my user changes his password then there is no way to connect to XMPP. 

The Owncloud jsxc plugin asks for login - but unless Owncloud and Jabber passwords are identical - login fails.

Is there a way to 
a) change the password on ejabberd o the XMPP server in general when the user changes his OC pwd
b) have different passwords for OC and XMPP (or even account names)?
I have checked "Allow User to owerwrite XMPP settings." - no avail. What is this option for whatsoever? Is it for having different account settings in oc and xmpp?

**Comment by sualko** [comment] 2015-06-03 08:23
I think this is a duplicate of #178.

If you checked "Allow User to owerwrite XMPP settings", your users are able to change there jid in the jsxc settings.

**Closed by sualko** 2015-06-03 08:23 UTC
Labels: duplicate
