### ISSUE TITLE
Registration of Managed (Beta service) failed

### ISSUE THREAD

**Issue by Rik44444** [jsxc/jsxc#939] opened 2020-09-20 18:04 UTC
### Expected behavior
Registration of Managed (Beta service) 

### Actual behavior

Sorry we couldn't complete your registration. 
Couldn't reach the registration server
Please report this to our issue tracker and mention the request id 2RmdcwTJYliLIPLGV7Wo.

### Steps to reproduce the behavior
1. Go to JSXC settings and register for managed beta service
2. Change nothing, enable "Enable chat on log in"
3. Check privacy and warranty boxes
4. register

### Environment
- **JSXC version: 4.1.1
- **Host system and version: 
NC 19.0.2
PHP Version: 7.3.22
Type: mysql
Version: 5.5.65 
- **Browser vendor and version: Firefox 80.0.1
- **Any browser plugins enabled? yes, many
- **XMPP server vendor and version:** 
- **Is your XMPP server working with other clients as expected?** 

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

**Comment by MarcelWaldvogel** [comment] 2020-09-21 10:17
Sorry, one of our DNS servers had been desynchronized. It should be fixed now, can you try again? Thanks!

**Comment by Rik44444** [comment] 2020-09-21 10:24
yes it worked:). But now when I want to set the chat to "Online" i have to enter a user name and password. 
1. what is the password?
2. will all users of our NC have to do this now? It was easier earlier when 'it just worked'

**Comment by MarcelWaldvogel** [comment] 2020-09-21 11:27
That should not be the case. There are no per-user passwords defined for the Managed Server. Instead, the Nextcloud-server-side component of JSXC (the PHP code) just creates a short-lived authentication token, which the client-side JSXC code (JavaScript in the Browser) uses to authenticate against the Managed Server. In effect, any user the Nextcloud server claims to have is automatically active on the Managed Server.

Did you logout and login? If it persists, can you provide more information?

Cc: @sualko

**Comment by Rik44444** [comment] 2020-09-21 12:13
yes it persists, also after restarting browser and logging out and logging in. 
The chat window on the right opens on "you are currently offline" and when I set it to "online" i get the image below

![image](https://user-images.githubusercontent.com/42555414/93765094-a110ce00-fc14-11ea-90f5-1f19a079463f.png)

**Comment by MarcelWaldvogel** [comment] 2020-09-21 20:19
I do not see any login attempt from your site in our XMPP server logs after the site was created. So it seems that the JSXC client is unable to reach our XMPP server (https://xmpp.jsxc.ch/http-bind/). Is there anything in your web browser console or in your browser's network traffic?

Can you also check the JSXC settings in Nextcloud, both in the "Personal" section (there should just be the BOSH URL, https://xmpp.jsxc.ch/http-bind/) and the "Administration" section (don't send the "Secure API token" nor the "TURN secret").

Also, you might switch the "Server type" to "External" (the "Managed Server" is just an "External" server with auto-configuration and "Time-limited Tokens" support) and check whether the "Activate time-limited tokens (beta)" checkbox is on.

(Feel free to mail information you do not want to be published in a GitHub issue to marcel@jsxc.ch).

**Comment by sualko** [comment] 2020-10-06 11:45
As Marcel is indicating, the issue is probably that your browser is not able to reach our xmpp server. Please check your js console. You can also send some test credentials to klaus@jsxc.org.

**Closed** 2020-12-08 15:45 UTC
Labels: feedback needed, managed-backend
