### ISSUE TITLE
master/slave issue preventing multiple windows from displaying jsxc

### ISSUE THREAD

**Issue by andrei-pmbcn** [jsxc/jsxc#769] opened 2019-03-20 13:18 UTC
### Expected behavior
Jsxc should display in all browser tabs where it is initialized

### Actual behavior
Jsxc only displays in a single browser tab, which it identifies as the master tab, the other tabs (i.e. the slave tabs) throwing an error. This is due to jsxc.xmpp.conn being missing in the slave tabs.

### Steps to reproduce the behavior
launch jsxc in three separate browser tabs; the jsxc GUI will only show up in one of them and the others will throw errors.

### Environment
- **JSXC version:** 3.4.3
- **Host system and version:** Apache 2.4
- **Browser vendor and version:** Chrome 73
- **Any browser plugins enabled?** no
- **XMPP server vendor and version:** Ejabberd 19.02
- **Is your XMPP server working with other clients as expected?** not tested

#### Javascript

In the slave tabs:
```
State changed to INITIATING
State changed to PREVCONFOUND
check master
I am the slave.
UI State changed to INITIATING
Uncaught TypeError: Cannot read property 'caps' of null
    at Object.jsxc.xmpp.httpUpload.init (jsxc.js:12568)
    at HTMLDocument.<anonymous> (jsxc.js:12854)
    at HTMLDocument.dispatch (jquery-2.1.1.min.js:3)
    at HTMLDocument.r.handle (jquery-2.1.1.min.js:3)
    at Object.trigger (jquery-2.1.1.min.js:3)
    at HTMLDocument.<anonymous> (jquery-2.1.1.min.js:3)
    at Function.each (jquery-2.1.1.min.js:2)
    at n.fn.init.each (jquery-2.1.1.min.js:2)
    at n.fn.init.trigger (jquery-2.1.1.min.js:3)
    at Object.changeUIState (jsxc.js:1123)
```

Apologies for the minified line numbers in jquery-2.1.1.min.js, will provide source maps if you prefer, though these should not be necessary.

**Comment by sualko** [comment] 2019-03-20 13:42
I can't reproduce your issue, but I think it occurs if the http upload is not fully initialized. Will be fixed in the next release. Thanks for reporting and if you have time it would be awesome if you could also test the [first beta release of 4.0](https://www.jsxc.org/blog/2019/03/02/v4.0.0-beta1-released.html).

**Comment by andrei-pmbcn** [comment] 2019-03-20 14:50
I would test it, but the beta release contains a JSXC (case-sensitive, not jsxc) object that does not have an init method, and lacks a jsxc object, so I have no indication as to how I could get it to run.

**Closed** 2019-04-16 11:44 UTC
Labels: bug
