### ISSUE TITLE
[ownCloud app] enable travis and write tests

### ISSUE THREAD

**Issue by DeepDiver1975** [jsxc/jsxc#264] opened 2016-01-13 15:57 UTC

**Comment by sualko** [comment] 2016-01-13 21:23
Duplicate of #191.

But hints and experiences in how to do js testing in a peer to peer scenario are always welcome.

**Closed by sualko** 2016-01-13 21:23 UTC

**Comment by LEDfan** [comment] 2016-01-15 15:42
@DeepDiver1975 I'm preparing some unit tests for the PHP backend, can you link the repo (in organization) with travis?

**Comment by DeepDiver1975** [comment] 2016-01-15 15:58
> @DeepDiver1975 I'm preparing some unit tests for the PHP backend, can you link the repo (in organization) with travis? tnx

done - thx

**Comment by pmgouveia** [comment] 2017-02-26 20:04
a docker image with a browser installed, chromium or firefox...

then run the tests in the docker image..

https://chimp.readme.io/docs/cucumberjs

I don't known how to make it possible running the tests with two browsers open or how-to change between tabs...
