### ISSUE TITLE
registration failed : Couldn't parse the response. Response code: 500

### ISSUE THREAD

**Issue by stanelie** [jsxc/jsxc#610] opened 2017-08-28 13:43 UTC
### Expected behavior
Register on the server
### Actual behavior
registration failed
### Steps to reproduce the behavior
1. click on "register"
2.
3.

### Environment
- **JSXC version:**  hosted
- **Host system and version:**  Nextcloud 12.0.2
- **Browser vendor and version:** 
- **Any browser plugins enabled?** 
- **XMPP server vendor and version:**  hosted
- **Is your XMPP server working with other clients as expected?** 

#### Error message
in the Nextcloud admin panel, after clicking on register, I get the following error message : 
```
Sorry we couldn't complete your registration.
Couldn't parse the response. Response code: 500
Please report this to our issue tracker and mention the request id EfJwmQjJsa86xLLLjvhY.
```

**Comment by sualko** [comment] 2017-08-28 14:14
I close this as duplicate of #611, because the other one is a bit more verbose. Sorry for the inconvenience, we are working on this.

**Closed by sualko** 2017-08-28 14:14 UTC

**Comment by stanelie** [comment] 2017-08-28 14:15
Cool.
