### ISSUE TITLE
"Load old messages" does not allow scrolling upwards anymore

### ISSUE THREAD

**Issue by DBJRdev** [jsxc/jsxc#929] opened 2020-07-06 09:03 UTC
### Expected behavior
In a chat modal, click on "Ältere Nachrichten laden" (load old messages) and scroll upwards to see older messages

### Actual behavior
When clicking you can see the most recent older messages, but there's no possibility for scrolling upwards

### Steps to reproduce the behavior
1. In Nextcloud chat to someone you have chatted before
2. Click on "Ältere Nachrichten laden" ...

### Environment
- **JSXC version:** 4.1.1
- **Host system and version:** Nextcloud 18.0.6
- **Browser vendor and version:** Firefox 77 and 78 on Ubuntu Linux
- **Any browser plugins enabled?** all deactivated, so no interference
- **XMPP server vendor and version:** any
- **Is your XMPP server working with other clients as expected?** yes

**Comment by sualko** [comment] 2020-07-06 13:21
I guess it's a duplicate of #873.

**Closed by sualko** 2020-07-06 13:21 UTC
