### ISSUE TITLE
Invite someone to a MUC chat room

### ISSUE THREAD

**Issue by MarcelWaldvogel** [jsxc/jsxc#599] opened 2017-08-04 06:38 UTC
I did not find an option to invite someone to a room, neither in the roster nor in the room window. This would make adoption easier for converts from other chat systems.

**Comment by sualko** [comment] 2017-08-15 12:03
@shazvan275 https://www.bountysource.com/issues/47922568-invite-someone-to-a-muc-chat-room :wink:

**Comment by sualko** [comment] 2017-10-04 08:25
This is actually a duplicate of #341.

**Closed by sualko** 2017-10-04 08:25 UTC
Labels: enhancement
