### ISSUE TITLE
File transfer - no Access-Control-Allow-Origin header 

### ISSUE THREAD

**Issue by smilexcasper** [jsxc/jsxc#530] opened 2017-05-17 12:11 UTC
This is not repeated treatment, I have another error!!!
Which jsxc version number do you use?

    last version

Which browser and browser version do you use?

    Firefox 53.0.2

Do you have any browser plugins enabled?

    firebug

Do you see any errors in your javascript console?
 

> XMLHttpRequest cannot load https://192.168.1.200:5443/upload/5627c20b7457729e75b7a9bebf297dfa7d641042/DEcAUCpmlfBGDjuaHvQzlvHhSff43JjNPy4ugJHD/chat.txt. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.1.200' is therefore not allowed access.

Config:
port: 5443
    module: ejabberd_http
    tls: true
    certfile: 'CERTFILE'
    request_handlers:     
      "": mod_http_upload     

  mod_http_upload:
    docroot: "/var/www"
    put_url: "https://192.168.1.200:5443/upload"
    custom_headers:
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "OPTIONS, HEAD, GET, PUT"

**Comment by sualko** [comment] 2017-05-17 12:13
But this time, duplicate of #529. Please be patient.

**Closed by sualko** 2017-05-17 12:13 UTC
