### ISSUE TITLE
Videoconferencing feature

### ISSUE THREAD

**Issue by ostasevych** [jsxc/jsxc#917] opened 2020-06-20 09:42 UTC
**Is your feature request related to a problem? Please describe.**
Due to lockdown and work from home a lot of people need to organise the meetings online. JSCX provides a good p2p communication, but lacks of conferencing solution.

**Is your feature request related to a specific XEP?**
XEP-0180

**Describe the solution you'd like**
Please, add the conferencing solutions, which may allow to cover the request in organising multiparty audio and video conversations together with the chat.  For that you may use existing Jitsi Meet elaborations.

**Additional context**
(Co)turnserver may be needed for implementing this solution in order to provide the access being behind NAT.

**Comment by sualko** [comment] 2020-06-21 10:24
Duplicate of #3. As you can see from the low issue number, we would like to implement this for quite some time. But it's a lot of work and there are still more urgent features (at least from my point of view). If someone want to work on this, or sponsor the feature, I'm glad to help.

**Closed by sualko** 2020-06-21 10:24 UTC
Labels: enhancement
